"use strict";
const SUBJ=["生産の基本","設備の日常保全","効率化とロス","改善・解析","設備保全の基礎"];
const CC={"生産の基本":"#2878B8","設備の日常保全":"#23875A","効率化とロス":"#C47A18","改善・解析":"#8A5AA8","設備保全の基礎":"#D94841"};
const EDUCATION={
  "生産の基本":{title:"用語と基本概念の再整理",practice:"TPM・5S・QCD・標準作業を、現場の具体例とセットで整理。似た用語を比較する○×演習を実施する。"},
  "設備の日常保全":{title:"現物を使った日常点検訓練",practice:"清掃・給油・増し締めを実機で確認し、異音・漏れ・ゆるみ・油量の正常／異常写真を使って判定練習をする。"},
  "効率化とロス":{title:"ロスの見つけ方と数値化",practice:"設備停止・チョコ停・速度低下・不良の分類演習を行い、身近なラインデータからロスを計算する。"},
  "改善・解析":{title:"問題解決の型を実践",practice:"なぜなぜ分析・パレート図・特性要因図を、実際の困りごと1件に当てはめる短時間ワークを行う。"},
  "設備保全の基礎":{title:"保全方式と劣化の理解",practice:"予防保全・事後保全・予知保全の使い分け、故障モードと点検基準を設備事例で整理する。"}
};
let rows=[];let serverAvailable=false;let timer;let authenticated=false;
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function notify(m){const e=document.getElementById("toast");e.textContent=m;e.classList.add("show");clearTimeout(timer);timer=setTimeout(()=>e.classList.remove("show"),2400);}
function normalize(x){if(!x||!x.cats||!Number.isFinite(Number(x.total)))return null;return {...x,id:x.id||`${x.name||"unknown"}-${x.sentAt||x.date||Date.now()}`,name:x.name||"(未記入)",total:Number(x.total)||0,correct:Number(x.correct)||0,mastered:Number(x.mastered)||0,streak:Number(x.streak)||0,alerts:Array.isArray(x.alerts)?x.alerts:[],sentAt:x.sentAt||x.receivedAt||x.date,receivedAt:x.receivedAt||x.sentAt||x.date};}
function showLogin(message=""){authenticated=false;document.getElementById("manager-login").classList.add("show");document.getElementById("login-message").textContent=message;document.getElementById("manager-pin").focus();}
function hideLogin(){authenticated=true;document.getElementById("manager-login").classList.remove("show");document.getElementById("manager-pin").value="";document.getElementById("login-message").textContent="";}
async function checkAuth(){if(location.protocol==="file:"){showLogin("この画面はファイルとして開かれています。start-server.bat を実行し、http://localhost:8787/admin.html から開いてください。");return;}try{const r=await fetch("./api/manager/status",{cache:"no-store"});if(!r.ok)throw new Error();const j=await r.json();if(j.authenticated){hideLogin();await loadRows(true);}else showLogin();}catch(e){showLogin("LANサーバーから開いてください。ファイルを直接開くと認証できません。");}}
async function login(){if(location.protocol==="file:"){showLogin("PINの問題ではありません。start-server.bat を実行し、http://localhost:8787/admin.html から開いてください。");return;}const pin=document.getElementById("manager-pin").value.trim(),btn=document.getElementById("login-btn");if(!pin)return;btn.disabled=true;btn.textContent="確認中…";try{const r=await fetch("./api/manager/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({pin}),cache:"no-store"});if(r.ok){hideLogin();await loadRows(true);notify("マネージャーにログインしました");}else if(r.status===429){const j=await r.json().catch(()=>({}));showLogin(j.message||"しばらく待ってから再試行してください。");}else showLogin("PINが違います。");}catch(e){showLogin("LANサーバーに接続できません。start-server.bat の黒い画面が起動中か確認し、http://localhost:8787/admin.html から開いてください。");}finally{btn.disabled=false;btn.textContent="ログイン";}}
async function logout(){try{await fetch("./api/manager/logout",{method:"POST"});}catch(e){}rows=[];render();showLogin("ログアウトしました。");}
function setConnection(){const dot=document.getElementById("connection-dot"),txt=document.getElementById("connection-text");dot.classList.toggle("online",serverAvailable);txt.textContent=serverAvailable?"LANサーバー受信中":"サーバー未接続";document.getElementById("submission-count").textContent=`${rows.length}件`;}
async function loadRows(silent=false){if(!authenticated)return;serverAvailable=false;try{const res=await fetch("./api/submissions",{cache:"no-store"});if(res.status===401){showLogin("認証の有効期限が切れました。");return;}if(!res.ok)throw new Error();const json=await res.json();rows=(Array.isArray(json.submissions)?json.submissions:[]).map(normalize).filter(Boolean).sort((a,b)=>new Date(b.receivedAt||b.sentAt)-new Date(a.receivedAt||a.sentAt));serverAvailable=true;}catch(e){rows=[];}setConnection();render();if(!silent)notify(serverAvailable?"提出データを更新しました":"サーバーに接続できません");}
function pct(n,d){return d?Math.round(n/d*100):null;}
function median(arr){if(!arr.length)return 0;const s=[...arr].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2;}
function stddev(arr){if(!arr.length)return 0;const m=arr.reduce((a,b)=>a+b,0)/arr.length;return Math.sqrt(arr.reduce((a,b)=>a+(b-m)**2,0)/arr.length);}
function fmtDate(v){if(!v)return"–";const d=new Date(v);if(Number.isNaN(d.getTime()))return esc(v);return d.toLocaleString("ja-JP",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"});}
function svgRadar(data){const w=360,h=280,cx=180,cy=134,r=88,levels=5;let out=`<svg viewBox="0 0 ${w} ${h}" aria-label="科目別レーダーチャート">`;for(let l=1;l<=levels;l++){const rr=r*l/levels,pts=data.map((_,i)=>{const a=-Math.PI/2+Math.PI*2*i/data.length;return`${(cx+Math.cos(a)*rr).toFixed(1)},${(cy+Math.sin(a)*rr).toFixed(1)}`});out+=`<polygon points="${pts.join(" ")}" fill="none" stroke="#d8dee5"/>`;}data.forEach((d,i)=>{const a=-Math.PI/2+Math.PI*2*i/data.length,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r,lx=cx+Math.cos(a)*(r+38),ly=cy+Math.sin(a)*(r+28);out+=`<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="#d8dee5"/><text x="${lx}" y="${ly}" text-anchor="middle" font-size="11" fill="#68737e">${esc(d.short)}</text><text x="${lx}" y="${ly+13}" text-anchor="middle" font-size="11" font-weight="700" fill="#20262d">${d.value}%</text>`;});const pts=data.map((d,i)=>{const a=-Math.PI/2+Math.PI*2*i/data.length,rr=r*d.value/100;return`${(cx+Math.cos(a)*rr).toFixed(1)},${(cy+Math.sin(a)*rr).toFixed(1)}`});out+=`<polygon points="${pts.join(" ")}" fill="rgba(40,120,184,.18)" stroke="#2878B8" stroke-width="2"/></svg>`;return out;}
function svgBars(data){const w=520,h=220,ml=116,mr=42,mt=10,barH=22,gap=14,gw=w-ml-mr;let out=`<svg viewBox="0 0 ${w} ${h}" aria-label="科目別平均正答率">`;data.forEach((d,i)=>{const y=mt+i*(barH+gap),bw=gw*d.value/100;out+=`<text x="8" y="${y+15}" font-size="12" fill="#68737e">${esc(d.label)}</text><rect x="${ml}" y="${y}" width="${gw}" height="${barH}" rx="6" fill="#e5e9ed"/><rect x="${ml}" y="${y}" width="${bw}" height="${barH}" rx="6" fill="${d.color}"/><text x="${ml+gw+8}" y="${y+15}" font-size="12" font-weight="800" fill="#20262d">${d.value}%</text>`;});return out+"</svg>";}
function analyze(){const accs=rows.map(r=>r.total?r.correct/r.total*100:0),answers=rows.map(r=>r.total),cats={};SUBJ.forEach(c=>cats[c]={c:0,t:0});const weak={};rows.forEach(r=>{for(const c in r.cats){if(!cats[c])cats[c]={c:0,t:0};cats[c].c+=Number(r.cats[c].c)||0;cats[c].t+=Number(r.cats[c].t)||0;}(r.alerts||[]).forEach(a=>{const k=a.id??a.text;if(!weak[k])weak[k]={id:a.id,text:a.text,cat:a.cat,n:0,names:new Set()};weak[k].names.add(r.name);weak[k].n=weak[k].names.size;});});const shorts=["生産基本","日常保全","効率・ロス","改善・解析","保全基礎"];const catData=SUBJ.map((c,i)=>({label:c,short:shorts[i],value:pct(cats[c].c,cats[c].t)||0,color:CC[c],sample:cats[c].t}));return{avg:rows.length?Math.round(accs.reduce((a,b)=>a+b,0)/rows.length):0,med:Math.round(median(accs)),sd:Math.round(stddev(accs)),range:accs.length?Math.round(Math.max(...accs)-Math.min(...accs)):0,avgAnswers:rows.length?Math.round(answers.reduce((a,b)=>a+b,0)/rows.length):0,today:rows.filter(r=>new Date(r.receivedAt||r.sentAt).toDateString()===new Date().toDateString()).length,mastered:rows.length?Math.round(rows.reduce((a,r)=>a+r.mastered,0)/rows.length):0,avgAlerts:rows.length?Math.round(rows.reduce((a,r)=>a+r.alerts.length,0)/rows.length*10)/10:0,catData,weak:Object.values(weak).sort((a,b)=>b.n-a.n).slice(0,10)};}
function levelFor(score){if(score<60)return{label:"基礎再教育",cls:"danger",plan:"30分の基礎説明 → 実例確認 → 10問演習 → 3日後に再テスト"};if(score<75)return{label:"重点補講",cls:"warn",plan:"15分のミニ講義 → 代表問題5問 → 間違い解説 → 1週間後に確認"};if(score<85)return{label:"弱点演習",cls:"info",plan:"苦手問題を5問選び、理由を説明させる演習。翌日に短時間復習"};return{label:"維持・発展",cls:"good",plan:"現場事例への応用問題と月1回の確認テスト"};}
function individualAdvice(r){const total=r.total||0,acc=total?Math.round(r.correct/total*100):0;let weakCat=null,weakRate=101;SUBJ.forEach(c=>{const x=r.cats[c];if(x&&x.t){const v=Math.round(x.c/x.t*100);if(v<weakRate){weakRate=v;weakCat=c;}}});if(total<30)return{level:"データ不足",cls:"info",text:`まず30問以上を回答して傾向を確認。現在は${total}問のため、教育判断は仮置き。`};if(acc<60)return{level:"個別基礎フォロー",cls:"danger",text:`${weakCat||"基礎項目"}を中心に、指導者同席で10問ずつ確認。正解だけでなく理由を口頭説明する。`};if(acc<75)return{level:"重点補講",cls:"warn",text:`最弱科目「${weakCat}」を15分補講し、誤答問題を翌日と3日後に再演習。`};if((r.alerts||[]).length>=5)return{level:"定着フォロー",cls:"warn",text:`正答率は${acc}%だが要注意が${r.alerts.length}問。1日・3日・7日の間隔で復習し、まぐれ正解を減らす。`};if(acc>=90)return{level:"応用・教える役",cls:"good",text:`理解度が高い。現場事例問題や、他者へ説明する役割で理解をさらに定着させる。`};return{level:"弱点演習",cls:"info",text:`「${weakCat}」の代表問題5問を理由付きで解き、1週間後に再確認する。`};}
function educationHtml(a){const valid=a.catData.filter(x=>x.sample>0),weakest=[...valid].sort((x,y)=>x.value-y.value)[0],second=[...valid].sort((x,y)=>x.value-y.value)[1];if(!weakest)return"";const lev=levelFor(weakest.value),content=EDUCATION[weakest.label]||{title:"弱点科目の補強",practice:"代表問題と現場事例を組み合わせて補講する。"};const recs=[];
  if(a.avgAnswers<30)recs.push({pri:"A",cls:"warn",title:"まず診断データを増やす",body:`1人平均${a.avgAnswers}問です。最低30問、できれば各科目10問以上を回答してから本格的な教育判断を行う。`});
  recs.push({pri:a.avgAnswers<30?"B":"A",cls:lev.cls,title:`最優先科目：${weakest.label}（${weakest.value}%）`,body:`${lev.label}。${content.title}：${content.practice} 実施手順は「${lev.plan}」。`});
  if(second&&second.value<75)recs.push({pri:"B",cls:"warn",title:`第2優先：${second.label}（${second.value}%）`,body:`最優先科目の補講後、代表問題5問と現場事例1件で短時間フォローする。`});
  if(a.sd>=12||a.range>=25)recs.push({pri:"A",cls:"info",title:"一斉教育ではなく2グループ化",body:`正答率のばらつきは標準偏差${a.sd}pt、最大差${a.range}pt。70%未満は基礎組、85%以上は応用組に分けると教育効率が上がる。`});
  else recs.push({pri:"C",cls:"good",title:"全体教育が成立しやすい",body:`受講者間のばらつきは比較的小さいため、弱点科目を全員で15分補講し、その後に個別復習へ分ける。`});
  if(a.mastered<10||a.avgAlerts>=5)recs.push({pri:"B",cls:"warn",title:"定着を狙う反復教育",body:`平均定着${a.mastered}問、平均要注意${a.avgAlerts}問。補講だけで終わらせず、1日後・3日後・7日後に同テーマを短時間で再出題する。`});
  recs.push({pri:"C",cls:"info",title:"1週間の実施例",body:"月：弱点科目15分補講／火：5問演習／木：誤答だけ再演習／翌月：確認テスト。1回を長くするより、短時間を複数回に分ける。"});
  let h=`<div class="manager-section ai-education"><div class="manager-section-head ai-head"><div><h2>AI教育コーチ</h2><p>統計から、次に実施する教育を提案します。</p></div><span class="ai-local-badge">ローカル分析・外部送信なし</span></div><div class="ai-overview"><div><span>今週の最優先</span><b>${esc(weakest.label)}</b><small>平均 ${weakest.value}% ／ ${lev.label}</small></div><div class="ai-score-ring">${a.avg}<small>%</small><span>全体平均</span></div></div><div class="ai-recommend-grid">`;
  recs.forEach(r=>h+=`<article class="ai-rec ${r.cls}"><div class="ai-priority">優先度 ${r.pri}</div><h3>${esc(r.title)}</h3><p>${esc(r.body)}</p></article>`);h+='</div><div class="ai-person-title"><h3>個人別フォロー案</h3><p>個人名を含むため、マネージャーだけが確認してください。</p></div><div class="ai-person-list">';
  rows.forEach(r=>{const x=individualAdvice(r),acc=r.total?Math.round(r.correct/r.total*100):0;h+=`<article class="ai-person ${x.cls}"><div class="ai-person-head"><b>${esc(r.name)}</b><span>${acc}% ／ ${r.total}問</span></div><strong>${esc(x.level)}</strong><p>${esc(x.text)}</p></article>`;});return h+'</div><div class="ai-disclaimer">この提案は統計ルールに基づくローカル分析です。正式な生成AIへ個人データを送信していないため、社内ネットワーク内で完結します。教育内容は現場責任者が最終判断してください。</div></div>';}
function statCard(label,value,sub=""){return`<div class="manager-stat-card"><span>${esc(label)}</span><b>${esc(value)}</b>${sub?`<small>${esc(sub)}</small>`:""}</div>`;}
function render(){const B=document.getElementById("ad-rep");if(!rows.length){B.innerHTML='<div class="manager-empty"><div>📭</div><b>提出データはまだありません</b><p>プレイヤーが「マネージャーへ送付」を押すと、ここへ自動表示されます。</p></div>';return;}const a=analyze();let h=`<div class="manager-stat-grid">${statCard("提出人数",rows.length+"名")}${statCard("本日の提出",a.today+"件")}${statCard("平均正答率",a.avg+"%")}${statCard("平均定着数",a.mastered+"問")}</div>`;
 h+=educationHtml(a);
 h+=`<div class="manager-section"><div class="manager-section-head"><div><h2>最近の提出</h2><p>誰が、いつ提出したかを確認できます。</p></div></div><div class="submission-list">`;rows.slice(0,12).forEach(r=>{const acc=r.total?Math.round(r.correct/r.total*100):0;h+=`<article class="submission-card"><div class="submission-avatar">${esc((r.name||"?").slice(0,1))}</div><div class="submission-main"><div class="submission-name">${esc(r.name)}</div><div class="submission-time">${fmtDate(r.receivedAt||r.sentAt)}</div><div class="submission-meta"><span>回答 ${r.total}問</span><span>正答率 ${acc}%</span><span>要注意 ${r.alerts.length}問</span></div></div><div class="submission-score">${acc}<small>%</small></div></article>`;});h+='</div></div>';
 h+=`<div class="manager-section"><div class="manager-section-head"><div><h2>科目別バランス</h2><p>全提出者の平均値です。</p></div></div><div class="manager-chart">${svgRadar(a.catData)}</div></div>`;
 h+=`<div class="manager-section"><div class="manager-section-head"><div><h2>科目別平均正答率</h2><p>弱い科目を比較します。</p></div></div><div class="manager-chart wide">${svgBars(a.catData)}</div></div>`;
 if(a.weak.length){h+=`<div class="manager-section"><div class="manager-section-head"><div><h2>教育の重点問題</h2><p>複数人が要注意として残している問題です。</p></div></div><div class="weak-list">`;a.weak.forEach((w,i)=>{h+=`<div class="weak-card"><span class="weak-rank">${i+1}</span><div><b>${esc(w.text)}</b><p>${esc(w.cat)} ／ ${w.n}名が要注意</p></div></div>`;});h+='</div></div>';}
 h+=`<div class="manager-section"><div class="manager-section-head"><div><h2>受講者別</h2><p>個人ごとの科目バランスです。</p></div></div>`;rows.forEach(r=>{const acc=r.total?Math.round(r.correct/r.total*100):0;h+=`<div class="manager-person"><div class="manager-person-head"><div><b>${esc(r.name)}</b><span>${fmtDate(r.receivedAt||r.sentAt)}</span></div><strong>${acc}<small>%</small></strong></div>`;SUBJ.forEach(c=>{const x=r.cats[c],v=x&&x.t?Math.round(x.c/x.t*100):null;h+=`<div class="manager-progress"><span>${esc(c)}</span><i><em style="width:${v||0}%;background:${CC[c]}"></em></i><b>${v===null?"–":v+"%"}</b></div>`;});h+=`<div class="manager-person-foot">回答 ${r.total}問　／　要注意 ${r.alerts.length}問　／　定着 ${r.mastered}問</div></div>`;});h+='</div>';B.innerHTML=h;}
function downloadCsv(){if(!rows.length){notify("提出データがありません");return;}const head=["氏名","送付日時","受信日時","総回答数","正解数","正答率","連続日数","要注意数","定着数",...SUBJ];const lines=[head];rows.forEach(r=>lines.push([r.name,r.sentAt,r.receivedAt,r.total,r.correct,r.total?Math.round(r.correct/r.total*100):0,r.streak,r.alerts.length,r.mastered,...SUBJ.map(c=>{const x=r.cats[c];return x&&x.t?Math.round(x.c/x.t*100):"";})]));const body=lines.map(row=>row.map(v=>'"'+String(v??"").replace(/"/g,'""')+'"').join(",")).join("\r\n");const b=new Blob(["\ufeff"+body],{type:"text/csv;charset=utf-8"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`skimaru_submissions_${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function clearAll(){if(!rows.length)return;if(!confirm("提出データをすべて削除しますか？"))return;try{const r=await fetch("./api/submissions",{method:"DELETE"});if(r.status===401){showLogin("認証の有効期限が切れました。");return;}}catch(e){}await loadRows(true);notify("提出データを削除しました");}
document.getElementById("login-btn").addEventListener("click",login);document.getElementById("manager-pin").addEventListener("keydown",e=>{if(e.key==="Enter")login();});document.getElementById("logout").addEventListener("click",logout);document.getElementById("refresh").addEventListener("click",()=>loadRows());document.getElementById("csv-learners").addEventListener("click",downloadCsv);document.getElementById("clear").addEventListener("click",clearAll);
checkAuth();setInterval(()=>{if(authenticated)loadRows(true);},15000);
