"use strict";
const CLOUD=window.SKIMARU_SUPABASE||{};
const SESSION_KEY="skimaru-supabase-manager-session-v1";
const SUBJ=["生産の基本","設備の日常保全","効率化とロス","改善・解析","設備保全の基礎"];
const CC={"生産の基本":"#2878B8","設備の日常保全":"#23875A","効率化とロス":"#C47A18","改善・解析":"#8A5AA8","設備保全の基礎":"#D94841"};
let rows=[],groups=[],serverAvailable=false,timer,authenticated=false,session=readSession();
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function notify(m){const e=document.getElementById("toast");e.textContent=m;e.classList.add("show");clearTimeout(timer);timer=setTimeout(()=>e.classList.remove("show"),2400);}
function configured(){return /^https:\/\//.test(CLOUD.url||"")&&String(CLOUD.publishableKey||"").startsWith("sb_publishable_");}
function readSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||"null");}catch(e){return null;}}
function saveSession(v){session=v;try{v?localStorage.setItem(SESSION_KEY,JSON.stringify(v)):localStorage.removeItem(SESSION_KEY);}catch(e){}}
function authHeaders(token){return {apikey:CLOUD.publishableKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json"};}
function parse(v,f){if(v==null)return f;if(typeof v==="string"){try{return JSON.parse(v);}catch(e){return f;}}return v;}
function normalize(x){
 const raw=parse(x.raw_result,{}),cats=parse(x.category_results,raw.cats||{}),alerts=parse(x.weak_questions,raw.alerts||[]);
 const total=Number(x.total_questions??raw.total)||0,correct=Number(x.correct_count??x.score??raw.correct)||0;
 return {id:x.submission_id||x.id,playerNo:String(x.player_no||raw.playerNo||"").trim(),name:x.user_name||raw.name||"(未記入)",total,correct,rate:total?Math.round(correct/total*100):0,mastered:Number(x.mastered_count??raw.mastered)||0,streak:Number(x.streak??raw.streak)||0,alerts:Array.isArray(alerts)?alerts:[],cats:cats&&typeof cats==="object"?cats:{},sentAt:x.submitted_at||raw.sentAt||x.created_at,receivedAt:x.created_at||x.submitted_at||raw.sentAt};
}
function showLogin(message=""){authenticated=false;document.getElementById("manager-login").classList.add("show");document.getElementById("login-message").textContent=message;}
function hideLogin(){authenticated=true;document.getElementById("manager-login").classList.remove("show");document.getElementById("manager-password").value="";document.getElementById("login-message").textContent="";}
async function refreshSession(){if(!session?.refresh_token)return false;try{const r=await fetch(`${CLOUD.url}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{apikey:CLOUD.publishableKey,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:session.refresh_token}),cache:"no-store"});if(!r.ok)throw new Error();const j=await r.json();saveSession({...j,expires_at_ms:Date.now()+(Number(j.expires_in)||3600)*1000});return true;}catch(e){saveSession(null);return false;}}
async function ensureSession(){if(!session?.access_token)return false;if((session.expires_at_ms||0)>Date.now()+60000)return true;return refreshSession();}
async function checkAuth(){if(!configured()){showLogin("Supabase接続設定がありません。");return;}if(await ensureSession()){hideLogin();await loadRows(true);}else showLogin();}
async function login(){const email=document.getElementById("manager-email").value.trim(),password=document.getElementById("manager-password").value,btn=document.getElementById("login-btn");if(!email||!password){showLogin("メールアドレスとパスワードを入力してください。");return;}btn.disabled=true;btn.textContent="確認中…";try{const r=await fetch(`${CLOUD.url}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:CLOUD.publishableKey,"Content-Type":"application/json"},body:JSON.stringify({email,password}),cache:"no-store"});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error_description||j.msg||j.message||"ログインできませんでした");saveSession({...j,expires_at_ms:Date.now()+(Number(j.expires_in)||3600)*1000});hideLogin();await loadRows(true);notify("ログインしました");}catch(e){showLogin(e.message||"ログインできませんでした");}finally{btn.disabled=false;btn.textContent="ログイン";}}
async function logout(){saveSession(null);rows=[];groups=[];render();showLogin("ログアウトしました。");}
function fmtDate(v){if(!v)return"–";const d=new Date(v);return Number.isNaN(d.getTime())?esc(v):d.toLocaleString("ja-JP",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"});}
function signed(n){return `${n>0?"+":""}${n}pt`;}
function buildGroups(){
 const map=new Map();
 rows.forEach((r,i)=>{const key=r.playerNo||`LEGACY:${r.name}`;if(!map.has(key))map.set(key,{key,playerNo:r.playerNo||"旧データ",name:r.name,history:[]});map.get(key).history.push(r);});
 groups=[...map.values()].map(g=>{g.history.sort((a,b)=>new Date(a.receivedAt||a.sentAt)-new Date(b.receivedAt||b.sentAt));g.first=g.history[0];g.latest=g.history[g.history.length-1];g.previous=g.history.length>1?g.history[g.history.length-2]:null;g.best=Math.max(...g.history.map(x=>x.rate));g.changePrev=g.previous?g.latest.rate-g.previous.rate:null;g.changeFirst=g.latest.rate-g.first.rate;return g;}).sort((a,b)=>new Date(b.latest.receivedAt||b.latest.sentAt)-new Date(a.latest.receivedAt||a.latest.sentAt));
 const nameCounts={};groups.forEach(g=>nameCounts[g.name]=(nameCounts[g.name]||0)+1);groups.forEach(g=>g.sameName=nameCounts[g.name]>1);
}
function setConnection(){document.getElementById("connection-dot").classList.toggle("online",serverAvailable);document.getElementById("connection-text").textContent=serverAvailable?"Supabaseクラウド接続中":"クラウド未接続";document.getElementById("submission-count").textContent=`${groups.length}人／履歴${rows.length}件`;}
async function loadRows(silent=false){if(!authenticated)return;serverAvailable=false;if(!(await ensureSession())){showLogin("認証の有効期限が切れました。");return;}try{const endpoint=`${CLOUD.url}/rest/v1/${encodeURIComponent(CLOUD.table||"exam_results")}?select=*&order=created_at.desc&limit=5000`;const res=await fetch(endpoint,{headers:authHeaders(session.access_token),cache:"no-store"});if(!res.ok)throw new Error(await res.text());rows=(await res.json()).map(normalize);buildGroups();serverAvailable=true;}catch(e){rows=[];groups=[];if(!silent)notify("提出データを取得できません");}setConnection();render();if(!silent&&serverAvailable)notify("更新しました");}
function statCard(label,value,sub=""){return `<div class="manager-stat-card"><span>${label}</span><b>${value}</b>${sub?`<small>${sub}</small>`:""}</div>`;}
function trendSvg(history){if(history.length<2)return '<p class="manager-empty-small">グラフは2回目の提出から表示されます。</p>';const w=560,h=220,ml=42,mr=18,mt=20,mb=36,gw=w-ml-mr,gh=h-mt-mb;let out=`<svg viewBox="0 0 ${w} ${h}" aria-label="正答率推移">`;[0,25,50,75,100].forEach(v=>{const y=mt+gh*(1-v/100);out+=`<line x1="${ml}" y1="${y}" x2="${w-mr}" y2="${y}" stroke="#dfe5ea"/><text x="${ml-8}" y="${y+4}" text-anchor="end" font-size="11">${v}</text>`;});const pts=history.map((r,i)=>`${ml+gw*(i/(history.length-1))},${mt+gh*(1-r.rate/100)}`);out+=`<polyline points="${pts.join(" ")}" fill="none" stroke="#23875A" stroke-width="3"/>`;history.forEach((r,i)=>{const [x,y]=pts[i].split(',');out+=`<circle cx="${x}" cy="${y}" r="5" fill="#fff" stroke="#23875A" stroke-width="3"/><text x="${x}" y="${Number(y)-10}" text-anchor="middle" font-size="11" font-weight="800">${r.rate}%</text>`;});return out+"</svg>";}
function render(){const B=document.getElementById("ad-rep");if(!groups.length){B.innerHTML='<div class="manager-empty"><div>📭</div><b>提出データはまだありません</b><p>プレイヤーが提出すると表示されます。</p></div>';return;}const avg=Math.round(groups.reduce((a,g)=>a+g.latest.rate,0)/groups.length),today=rows.filter(r=>new Date(r.receivedAt||r.sentAt).toDateString()===new Date().toDateString()).length,improved=groups.filter(g=>g.changePrev>0).length;let h=`<div class="manager-stat-grid">${statCard("登録プレイヤー",groups.length+"人")}${statCard("提出履歴",rows.length+"件")}${statCard("最新平均",avg+"%")}${statCard("前回より成長",improved+"人",today+"件が本日提出")}</div>`;
 h+=`<div class="manager-section"><div class="manager-section-head"><div><h2>プレイヤー一覧</h2><p>1人1行で最新結果を表示。タップすると過去履歴を確認できます。</p></div></div><div class="player-table-wrap"><table class="player-table"><thead><tr><th>No.</th><th>表示名</th><th>最新</th><th>前回比</th><th>初回比</th><th>回数</th><th>最終提出</th></tr></thead><tbody>`;
 groups.forEach((g,i)=>{h+=`<tr class="player-row" data-group="${i}" tabindex="0"><td><b>${esc(g.playerNo)}</b></td><td>${esc(g.name)}${g.sameName?'<span class="same-name-badge">同名あり</span>':''}</td><td><strong>${g.latest.rate}%</strong><small>${g.latest.correct}/${g.latest.total}問</small></td><td class="${g.changePrev>0?'up':g.changePrev<0?'down':''}">${g.changePrev==null?'–':signed(g.changePrev)}</td><td class="${g.changeFirst>0?'up':g.changeFirst<0?'down':''}">${signed(g.changeFirst)}</td><td>${g.history.length}回</td><td>${fmtDate(g.latest.receivedAt||g.latest.sentAt)}</td></tr>`;});
 h+='</tbody></table></div></div>';B.innerHTML=h;B.querySelectorAll('.player-row').forEach(el=>{const open=()=>openDetail(groups[Number(el.dataset.group)]);el.addEventListener('click',open);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}});});}
function openDetail(g){const latest=g.latest;let h=`<div class="detail-head"><div><span class="detail-no">${esc(g.playerNo)}</span><h2>${esc(g.name)}${g.sameName?'<span class="same-name-badge">同名あり</span>':''}</h2><p>提出 ${g.history.length}回 ／ 最終 ${fmtDate(latest.receivedAt||latest.sentAt)}</p></div><strong>${latest.rate}<small>%</small></strong></div><div class="detail-stat-grid">${statCard("前回比",g.changePrev==null?"–":signed(g.changePrev))}${statCard("初回比",signed(g.changeFirst))}${statCard("過去最高",g.best+"%")}${statCard("最新回答数",latest.total+"問")}</div><div class="manager-section"><h2>正答率の推移</h2><div class="manager-chart wide">${trendSvg(g.history)}</div></div><div class="manager-section"><h2>提出履歴</h2><div class="history-list">`;
 [...g.history].reverse().forEach((r,i)=>{h+=`<div class="history-item"><div><b>${fmtDate(r.receivedAt||r.sentAt)}</b><span>${r.correct}/${r.total}問正解　要注意${r.alerts.length}問</span></div><strong>${r.rate}%</strong></div>`;});h+='</div></div>';document.getElementById('player-detail-body').innerHTML=h;const modal=document.getElementById('player-detail');modal.classList.add('show');modal.setAttribute('aria-hidden','false');}
function closeDetail(){const m=document.getElementById('player-detail');m.classList.remove('show');m.setAttribute('aria-hidden','true');}
function downloadCsv(){if(!rows.length){notify("提出データがありません");return;}const lines=[["プレイヤーNo.","表示名","提出日時","正解数","回答数","正答率"]];rows.forEach(r=>lines.push([r.playerNo||"旧データ",r.name,r.receivedAt||r.sentAt,r.correct,r.total,r.rate]));const body=lines.map(row=>row.map(v=>'"'+String(v??"").replace(/"/g,'""')+'"').join(',')).join('\r\n');const b=new Blob(["\ufeff"+body],{type:"text/csv;charset=utf-8"}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`skimaru_history_${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function clearAll(){if(!rows.length||!confirm("提出履歴をすべて削除しますか？")||!confirm("元に戻せません。本当に削除しますか？"))return;if(!(await ensureSession()))return;try{const endpoint=`${CLOUD.url}/rest/v1/${encodeURIComponent(CLOUD.table||"exam_results")}?id=not.is.null`;const r=await fetch(endpoint,{method:"DELETE",headers:{...authHeaders(session.access_token),Prefer:"return=minimal"}});if(!r.ok)throw new Error();rows=[];groups=[];setConnection();render();notify("削除しました");}catch(e){notify("削除できませんでした");}}
document.getElementById("login-btn").addEventListener("click",login);document.getElementById("manager-password").addEventListener("keydown",e=>{if(e.key==="Enter")login();});document.getElementById("logout").addEventListener("click",logout);document.getElementById("refresh").addEventListener("click",()=>loadRows());document.getElementById("csv-learners").addEventListener("click",downloadCsv);document.getElementById("clear").addEventListener("click",clearAll);document.getElementById("player-detail-close").addEventListener("click",closeDetail);document.getElementById("player-detail").addEventListener("click",e=>{if(e.target.id==="player-detail")closeDetail();});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeDetail();});
checkAuth();setInterval(()=>{if(authenticated)loadRows(true);},15000);
