"use strict";
const CLOUD=window.SKIMARU_SUPABASE||{};
const SESSION_KEY="skimaru-supabase-manager-session-v1";
const SUBJ=["生産の基本","設備の日常保全","効率化とロス","改善・解析","設備保全の基礎"];
const CC={"生産の基本":"#2878B8","設備の日常保全":"#23875A","効率化とロス":"#C47A18","改善・解析":"#8A5AA8","設備保全の基礎":"#D94841"};
const EDUCATION={
 "生産の基本":{title:"用語と基本概念の再整理",practice:"TPM・5S・QCD・標準作業を、現場の具体例とセットで整理。似た用語を比較する○×演習を実施する。"},
 "設備の日常保全":{title:"現物を使った日常点検訓練",practice:"清掃・給油・増し締めを実機で確認し、異音・漏れ・ゆるみ・油量の正常／異常写真を使って判定練習をする。"},
 "効率化とロス":{title:"ロスの見つけ方と数値化",practice:"設備停止・チョコ停・速度低下・不良の分類演習を行い、身近なラインデータからロスを計算する。"},
 "改善・解析":{title:"問題解決の型を実践",practice:"なぜなぜ分析・パレート図・特性要因図を、実際の困りごと1件に当てはめる短時間ワークを行う。"},
 "設備保全の基礎":{title:"保全方式と劣化の理解",practice:"予防保全・事後保全・予知保全の使い分け、故障モードと点検基準を設備事例で整理する。"}
};
let rows=[],groups=[],serverAvailable=false,timer,authenticated=false,session=readSession();
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
function notify(m){const e=document.getElementById("toast");e.textContent=m;e.classList.add("show");clearTimeout(timer);timer=setTimeout(()=>e.classList.remove("show"),2400);}
function configured(){return /^https:\/\//.test(CLOUD.url||"")&&String(CLOUD.publishableKey||"").startsWith("sb_publishable_");}
function readSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||"null");}catch(e){return null;}}
function saveSession(v){session=v;try{v?localStorage.setItem(SESSION_KEY,JSON.stringify(v)):localStorage.removeItem(SESSION_KEY);}catch(e){}}
function authHeaders(token){return {apikey:CLOUD.publishableKey,Authorization:`Bearer ${token}`,"Content-Type":"application/json"};}
function parse(v,f){if(v==null)return f;if(typeof v==="string"){try{return JSON.parse(v);}catch(e){return f;}}return v;}
function normalize(x){
 const raw=parse(x.raw_result,{}),cats=parse(x.category_results,raw.cats||{}),alerts=parse(x.weak_questions,raw.alerts||[]);
 const total=Number(x.total_questions??raw.total)||0,correct=Number(x.correct_count??x.score??raw.correct)||0;
 return {id:x.submission_id||x.id,playerNo:String(x.player_no||raw.playerNo||"").trim(),name:x.user_name||raw.name||"(未記入)",total,correct,rate:total?Math.round(correct/total*100):0,mastered:Number(x.mastered_count??raw.mastered)||0,streak:Number(x.streak??raw.streak)||0,alerts:Array.isArray(alerts)?alerts:[],cats:cats&&typeof cats==="object"?cats:{},sentAt:x.submitted_at||raw.sentAt||x.created_at,receivedAt:x.created_at||x.submitted_at||raw.sentAt};
}
function showLogin(message=""){authenticated=false;document.getElementById("manager-login").classList.add("show");document.getElementById("login-message").textContent=message;}
function hideLogin(){authenticated=true;document.getElementById("manager-login").classList.remove("show");document.getElementById("manager-password").value="";document.getElementById("login-message").textContent="";}
async function refreshSession(){if(!session?.refresh_token)return false;try{const r=await fetch(`${CLOUD.url}/auth/v1/token?grant_type=refresh_token`,{method:"POST",headers:{apikey:CLOUD.publishableKey,"Content-Type":"application/json"},body:JSON.stringify({refresh_token:session.refresh_token}),cache:"no-store"});if(!r.ok)throw new Error();const j=await r.json();saveSession({...j,expires_at_ms:Date.now()+(Number(j.expires_in)||3600)*1000});return true;}catch(e){saveSession(null);return false;}}
async function ensureSession(){if(!session?.access_token)return false;if((session.expires_at_ms||0)>Date.now()+60000)return true;return refreshSession();}
async function checkAuth(){if(!configured()){showLogin("Supabase接続設定がありません。");return;}if(await ensureSession()){hideLogin();await loadRows(true);}else showLogin();}
async function login(){const email=document.getElementById("manager-email").value.trim(),password=document.getElementById("manager-password").value,btn=document.getElementById("login-btn");if(!email||!password){showLogin("メールアドレスとパスワードを入力してください。");return;}btn.disabled=true;btn.textContent="確認中…";try{const r=await fetch(`${CLOUD.url}/auth/v1/token?grant_type=password`,{method:"POST",headers:{apikey:CLOUD.publishableKey,"Content-Type":"application/json"},body:JSON.stringify({email,password}),cache:"no-store"});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error_description||j.msg||j.message||"ログインできませんでした");saveSession({...j,expires_at_ms:Date.now()+(Number(j.expires_in)||3600)*1000});hideLogin();await loadRows(true);notify("ログインしました");}catch(e){showLogin(e.message||"ログインできませんでした");}finally{btn.disabled=false;btn.textContent="ログイン";}}
async function logout(){saveSession(null);rows=[];groups=[];render();showLogin("ログアウトしました。");}
function fmtDate(v){if(!v)return"–";const d=new Date(v);return Number.isNaN(d.getTime())?esc(v):d.toLocaleString("ja-JP",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"});}
function signed(n){return `${n>0?"+":""}${n}pt`;}
function buildGroups(){
 const map=new Map();
 rows.forEach((r,i)=>{const key=r.playerNo||`LEGACY:${r.name}`;if(!map.has(key))map.set(key,{key,playerNo:r.playerNo||"旧データ",name:r.name,history:[]});map.get(key).history.push(r);});
 groups=[...map.values()].map(g=>{g.history.sort((a,b)=>new Date(a.receivedAt||a.sentAt)-new Date(b.receivedAt||b.sentAt));g.first=g.history[0];g.latest=g.history[g.history.length-1];g.previous=g.history.length>1?g.history[g.history.length-2]:null;g.best=Math.max(...g.history.map(x=>x.rate));g.changePrev=g.previous?g.latest.rate-g.previous.rate:null;g.changeFirst=g.latest.rate-g.first.rate;return g;}).sort((a,b)=>new Date(b.latest.receivedAt||b.latest.sentAt)-new Date(a.latest.receivedAt||a.latest.sentAt));
 const nameCounts={};groups.forEach(g=>nameCounts[g.name]=(nameCounts[g.name]||0)+1);groups.forEach(g=>g.sameName=nameCounts[g.name]>1);
}
function setConnection(){document.getElementById("connection-dot").classList.toggle("online",serverAvailable);document.getElementById("connection-text").textContent=serverAvailable?"Supabaseクラウド接続中":"クラウド未接続";document.getElementById("submission-count").textContent=`${groups.length}人／履歴${rows.length}件`;}
async function loadRows(silent=false){if(!authenticated)return;serverAvailable=false;if(!(await ensureSession())){showLogin("認証の有効期限が切れました。");return;}try{const endpoint=`${CLOUD.url}/rest/v1/${encodeURIComponent(CLOUD.table||"exam_results")}?select=*&order=created_at.desc&limit=5000`;const res=await fetch(endpoint,{headers:authHeaders(session.access_token),cache:"no-store"});if(!res.ok)throw new Error(await res.text());rows=(await res.json()).map(normalize);buildGroups();serverAvailable=true;}catch(e){rows=[];groups=[];if(!silent)notify("提出データを取得できません");}setConnection();render();if(!silent&&serverAvailable)notify("更新しました");}
function pct(n,d){return d?Math.round(n/d*100):null;}
function median(values){if(!values.length)return 0;const sorted=[...values].sort((a,b)=>a-b),middle=Math.floor(sorted.length/2);return sorted.length%2?sorted[middle]:(sorted[middle-1]+sorted[middle])/2;}
function stddev(values){if(!values.length)return 0;const mean=values.reduce((a,b)=>a+b,0)/values.length;return Math.sqrt(values.reduce((sum,value)=>sum+(value-mean)**2,0)/values.length);}
function analysisRows(){return groups.map(group=>group.latest);}
function svgRadar(data){const w=360,h=280,cx=180,cy=134,r=88,levels=5;let out=`<svg viewBox="0 0 ${w} ${h}" aria-label="科目別レーダーチャート">`;for(let level=1;level<=levels;level++){const radius=r*level/levels,points=data.map((_,i)=>{const angle=-Math.PI/2+Math.PI*2*i/data.length;return`${(cx+Math.cos(angle)*radius).toFixed(1)},${(cy+Math.sin(angle)*radius).toFixed(1)}`;});out+=`<polygon points="${points.join(" ")}" fill="none" stroke="#d8dee5"/>`;}data.forEach((item,i)=>{const angle=-Math.PI/2+Math.PI*2*i/data.length,x=cx+Math.cos(angle)*r,y=cy+Math.sin(angle)*r,labelX=cx+Math.cos(angle)*(r+38),labelY=cy+Math.sin(angle)*(r+28);out+=`<line x1="${cx}" y1="${cy}" x2="${x}" y2="${y}" stroke="#d8dee5"/><text x="${labelX}" y="${labelY}" text-anchor="middle" font-size="11" fill="#68737e">${esc(item.short)}</text><text x="${labelX}" y="${labelY+13}" text-anchor="middle" font-size="11" font-weight="700" fill="#20262d">${item.value}%</text>`;});const points=data.map((item,i)=>{const angle=-Math.PI/2+Math.PI*2*i/data.length,radius=r*item.value/100;return`${(cx+Math.cos(angle)*radius).toFixed(1)},${(cy+Math.sin(angle)*radius).toFixed(1)}`;});return out+`<polygon points="${points.join(" ")}" fill="rgba(40,120,184,.18)" stroke="#2878B8" stroke-width="2"/></svg>`;}
function svgBars(data){const w=520,h=220,left=116,right=42,top=10,barHeight=22,gap=14,graphWidth=w-left-right;let out=`<svg viewBox="0 0 ${w} ${h}" aria-label="科目別平均正答率">`;data.forEach((item,i)=>{const y=top+i*(barHeight+gap),barWidth=graphWidth*item.value/100;out+=`<text x="8" y="${y+15}" font-size="12" fill="#68737e">${esc(item.label)}</text><rect x="${left}" y="${y}" width="${graphWidth}" height="${barHeight}" rx="6" fill="#e5e9ed"/><rect x="${left}" y="${y}" width="${barWidth}" height="${barHeight}" rx="6" fill="${item.color}"/><text x="${left+graphWidth+8}" y="${y+15}" font-size="12" font-weight="800" fill="#20262d">${item.value}%</text>`;});return out+"</svg>";}
function analyze(){
 const population=analysisRows(),accuracies=population.map(row=>row.rate),answers=population.map(row=>row.total),categories={};
 SUBJ.forEach(category=>categories[category]={c:0,t:0});
 const weak={};
 population.forEach(row=>{
  for(const category in row.cats){if(!categories[category])categories[category]={c:0,t:0};categories[category].c+=Number(row.cats[category].c)||0;categories[category].t+=Number(row.cats[category].t)||0;}
  (row.alerts||[]).forEach(alert=>{const key=alert.id??alert.text;if(!weak[key])weak[key]={id:alert.id,text:alert.text,cat:alert.cat,n:0,players:new Set()};weak[key].players.add(row.playerNo||row.name);weak[key].n=weak[key].players.size;});
 });
 const shorts=["生産基本","日常保全","効率・ロス","改善・解析","保全基礎"];
 const catData=SUBJ.map((category,i)=>({label:category,short:shorts[i],value:pct(categories[category].c,categories[category].t)||0,color:CC[category],sample:categories[category].t}));
 return {population,avg:population.length?Math.round(accuracies.reduce((a,b)=>a+b,0)/population.length):0,med:Math.round(median(accuracies)),sd:Math.round(stddev(accuracies)),range:accuracies.length?Math.round(Math.max(...accuracies)-Math.min(...accuracies)):0,avgAnswers:population.length?Math.round(answers.reduce((a,b)=>a+b,0)/population.length):0,today:rows.filter(row=>new Date(row.receivedAt||row.sentAt).toDateString()===new Date().toDateString()).length,mastered:population.length?Math.round(population.reduce((sum,row)=>sum+row.mastered,0)/population.length):0,avgAlerts:population.length?Math.round(population.reduce((sum,row)=>sum+row.alerts.length,0)/population.length*10)/10:0,catData,weak:Object.values(weak).sort((a,b)=>b.n-a.n).slice(0,10)};
}
function levelFor(score){if(score<60)return{label:"基礎再教育",cls:"danger",plan:"30分の基礎説明 → 実例確認 → 10問演習 → 3日後に再テスト"};if(score<75)return{label:"重点補講",cls:"warn",plan:"15分のミニ講義 → 代表問題5問 → 間違い解説 → 1週間後に確認"};if(score<85)return{label:"弱点演習",cls:"info",plan:"苦手問題を5問選び、理由を説明させる演習。翌日に短時間復習"};return{label:"維持・発展",cls:"good",plan:"現場事例への応用問題と月1回の確認テスト"};}
function individualAdvice(row){const total=row.total||0,accuracy=row.rate;let weakCategory=null,weakRate=101;SUBJ.forEach(category=>{const result=row.cats[category];if(result&&result.t){const value=Math.round(result.c/result.t*100);if(value<weakRate){weakRate=value;weakCategory=category;}}});if(total<30)return{level:"データ不足",cls:"info",text:`まず30問以上を回答して傾向を確認。現在は${total}問のため、教育判断は仮置き。`};if(accuracy<60)return{level:"個別基礎フォロー",cls:"danger",text:`${weakCategory||"基礎項目"}を中心に、指導者同席で10問ずつ確認。正解だけでなく理由を口頭説明する。`};if(accuracy<75)return{level:"重点補講",cls:"warn",text:`最弱科目「${weakCategory||"基礎項目"}」を15分補講し、誤答問題を翌日と3日後に再演習。`};if((row.alerts||[]).length>=5)return{level:"定着フォロー",cls:"warn",text:`正答率は${accuracy}%だが要注意が${row.alerts.length}問。1日・3日・7日の間隔で復習し、まぐれ正解を減らす。`};if(accuracy>=90)return{level:"応用・教える役",cls:"good",text:"理解度が高い。現場事例問題や、他者へ説明する役割で理解をさらに定着させる。"};return{level:"弱点演習",cls:"info",text:`「${weakCategory||"基礎項目"}」の代表問題5問を理由付きで解き、1週間後に再確認する。`};}
function educationHtml(analysis){
 const valid=analysis.catData.filter(item=>item.sample>0),weakest=[...valid].sort((a,b)=>a.value-b.value)[0],second=[...valid].sort((a,b)=>a.value-b.value)[1];
 if(!weakest)return '<div class="manager-section"><div class="manager-empty-small">科目別データがある提出から全体傾向を表示します。</div></div>';
 const level=levelFor(weakest.value),content=EDUCATION[weakest.label]||{title:"弱点科目の補強",practice:"代表問題と現場事例を組み合わせて補講する。"},recommendations=[];
 if(analysis.avgAnswers<30)recommendations.push({pri:"A",cls:"warn",title:"まず診断データを増やす",body:`1人平均${analysis.avgAnswers}問です。最低30問、できれば各科目10問以上を回答してから本格的な教育判断を行う。`});
 recommendations.push({pri:analysis.avgAnswers<30?"B":"A",cls:level.cls,title:`最優先科目：${weakest.label}（${weakest.value}%）`,body:`${level.label}。${content.title}：${content.practice} 実施手順は「${level.plan}」。`});
 if(second&&second.value<75)recommendations.push({pri:"B",cls:"warn",title:`第2優先：${second.label}（${second.value}%）`,body:"最優先科目の補講後、代表問題5問と現場事例1件で短時間フォローする。"});
 if(analysis.sd>=12||analysis.range>=25)recommendations.push({pri:"A",cls:"info",title:"一斉教育ではなく2グループ化",body:`正答率のばらつきは標準偏差${analysis.sd}pt、最大差${analysis.range}pt。70%未満は基礎組、85%以上は応用組に分けると教育効率が上がる。`});
 else recommendations.push({pri:"C",cls:"good",title:"全体教育が成立しやすい",body:"受講者間のばらつきは比較的小さいため、弱点科目を全員で15分補講し、その後に個別復習へ分ける。"});
 if(analysis.mastered<10||analysis.avgAlerts>=5)recommendations.push({pri:"B",cls:"warn",title:"定着を狙う反復教育",body:`平均定着${analysis.mastered}問、平均要注意${analysis.avgAlerts}問。補講だけで終わらせず、1日後・3日後・7日後に同テーマを短時間で再出題する。`});
 recommendations.push({pri:"C",cls:"info",title:"1週間の実施例",body:"月：弱点科目15分補講／火：5問演習／木：誤答だけ再演習／翌月：確認テスト。1回を長くするより、短時間を複数回に分ける。"});
 let html=`<div class="manager-section ai-education"><div class="manager-section-head ai-head"><div><h2>AI教育コーチ</h2><p>各プレイヤーの最新提出から、次に実施する教育を提案します。</p></div><span class="ai-local-badge">端末内分析・生成AI送信なし</span></div><div class="ai-overview"><div><span>今週の最優先</span><b>${esc(weakest.label)}</b><small>平均 ${weakest.value}% ／ ${level.label}</small></div><div class="ai-score-ring">${analysis.avg}<small>%</small><span>全体平均</span></div></div><div class="ai-recommend-grid">`;
 recommendations.forEach(item=>html+=`<article class="ai-rec ${item.cls}"><div class="ai-priority">優先度 ${item.pri}</div><h3>${esc(item.title)}</h3><p>${esc(item.body)}</p></article>`);
 html+='</div><div class="ai-person-title"><h3>個人別フォロー案</h3><p>各プレイヤーの最新提出を基準にしています。</p></div><div class="ai-person-list">';
 analysis.population.forEach(row=>{const advice=individualAdvice(row);html+=`<article class="ai-person ${advice.cls}"><div class="ai-person-head"><b>${esc(row.name)}</b><span>${row.rate}% ／ ${row.total}問</span></div><strong>${esc(advice.level)}</strong><p>${esc(advice.text)}</p></article>`;});
 return html+'</div><div class="ai-disclaimer">この提案は、Supabaseから取得した統計をブラウザ内のルールで分析しています。個人データを生成AIサービスへ送信していません。教育内容は現場責任者が最終判断してください。</div></div>';
}
function statCard(label,value,sub=""){return `<div class="manager-stat-card"><span>${label}</span><b>${value}</b>${sub?`<small>${sub}</small>`:""}</div>`;}
function trendSvg(history){if(history.length<2)return '<p class="manager-empty-small">グラフは2回目の提出から表示されます。</p>';const w=560,h=220,ml=42,mr=18,mt=20,mb=36,gw=w-ml-mr,gh=h-mt-mb;let out=`<svg viewBox="0 0 ${w} ${h}" aria-label="正答率推移">`;[0,25,50,75,100].forEach(v=>{const y=mt+gh*(1-v/100);out+=`<line x1="${ml}" y1="${y}" x2="${w-mr}" y2="${y}" stroke="#dfe5ea"/><text x="${ml-8}" y="${y+4}" text-anchor="end" font-size="11">${v}</text>`;});const pts=history.map((r,i)=>`${ml+gw*(i/(history.length-1))},${mt+gh*(1-r.rate/100)}`);out+=`<polyline points="${pts.join(" ")}" fill="none" stroke="#23875A" stroke-width="3"/>`;history.forEach((r,i)=>{const [x,y]=pts[i].split(',');out+=`<circle cx="${x}" cy="${y}" r="5" fill="#fff" stroke="#23875A" stroke-width="3"/><text x="${x}" y="${Number(y)-10}" text-anchor="middle" font-size="11" font-weight="800">${r.rate}%</text>`;});return out+"</svg>";}
function render(){const B=document.getElementById("ad-rep");if(!groups.length){B.innerHTML='<div class="manager-empty"><div>📭</div><b>提出データはまだありません</b><p>プレイヤーが提出すると表示されます。</p></div>';return;}const analysis=analyze(),improved=groups.filter(group=>group.changePrev>0).length;let h=`<div class="manager-stat-grid">${statCard("登録プレイヤー",groups.length+"人")}${statCard("提出履歴",rows.length+"件")}${statCard("最新平均",analysis.avg+"%")}${statCard("前回より成長",improved+"人",analysis.today+"件が本日提出")}</div>`;
 h+=educationHtml(analysis);
 h+=`<div class="manager-section"><div class="manager-section-head"><div><h2>科目別バランス</h2><p>各プレイヤーの最新提出による全体平均です。</p></div></div><div class="manager-chart">${svgRadar(analysis.catData)}</div></div>`;
 h+=`<div class="manager-section"><div class="manager-section-head"><div><h2>科目別平均正答率</h2><p>参加者全体の弱い科目を比較します。</p></div></div><div class="manager-chart wide">${svgBars(analysis.catData)}</div></div>`;
 if(analysis.weak.length){h+=`<div class="manager-section"><div class="manager-section-head"><div><h2>教育の重点問題</h2><p>複数のプレイヤーが要注意として残している問題です。</p></div></div><div class="weak-list">`;analysis.weak.forEach((item,i)=>{h+=`<div class="weak-card"><span class="weak-rank">${i+1}</span><div><b>${esc(item.text)}</b><p>${esc(item.cat)} ／ ${item.n}名が要注意</p></div></div>`;});h+='</div></div>';}
 h+=`<div class="manager-section"><div class="manager-section-head"><div><h2>プレイヤー一覧</h2><p>1人1行で最新結果を表示。タップすると過去履歴を確認できます。</p></div></div><div class="player-table-wrap"><table class="player-table"><thead><tr><th>No.</th><th>表示名</th><th>最新</th><th>前回比</th><th>初回比</th><th>回数</th><th>最終提出</th></tr></thead><tbody>`;
 groups.forEach((g,i)=>{h+=`<tr class="player-row" data-group="${i}" tabindex="0"><td><b>${esc(g.playerNo)}</b></td><td>${esc(g.name)}${g.sameName?'<span class="same-name-badge">同名あり</span>':''}</td><td><strong>${g.latest.rate}%</strong><small>${g.latest.correct}/${g.latest.total}問</small></td><td class="${g.changePrev>0?'up':g.changePrev<0?'down':''}">${g.changePrev==null?'–':signed(g.changePrev)}</td><td class="${g.changeFirst>0?'up':g.changeFirst<0?'down':''}">${signed(g.changeFirst)}</td><td>${g.history.length}回</td><td>${fmtDate(g.latest.receivedAt||g.latest.sentAt)}</td></tr>`;});
 h+='</tbody></table></div></div>';B.innerHTML=h;B.querySelectorAll('.player-row').forEach(el=>{const open=()=>openDetail(groups[Number(el.dataset.group)]);el.addEventListener('click',open);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}});});}
function openDetail(g){const latest=g.latest;let h=`<div class="detail-head"><div><span class="detail-no">${esc(g.playerNo)}</span><h2>${esc(g.name)}${g.sameName?'<span class="same-name-badge">同名あり</span>':''}</h2><p>提出 ${g.history.length}回 ／ 最終 ${fmtDate(latest.receivedAt||latest.sentAt)}</p></div><strong>${latest.rate}<small>%</small></strong></div><div class="detail-stat-grid">${statCard("前回比",g.changePrev==null?"–":signed(g.changePrev))}${statCard("初回比",signed(g.changeFirst))}${statCard("過去最高",g.best+"%")}${statCard("最新回答数",latest.total+"問")}</div><div class="manager-section"><h2>正答率の推移</h2><div class="manager-chart wide">${trendSvg(g.history)}</div></div><div class="manager-section"><h2>提出履歴</h2><div class="history-list">`;
 [...g.history].reverse().forEach((r,i)=>{h+=`<div class="history-item"><div><b>${fmtDate(r.receivedAt||r.sentAt)}</b><span>${r.correct}/${r.total}問正解　要注意${r.alerts.length}問</span></div><strong>${r.rate}%</strong></div>`;});h+='</div></div>';document.getElementById('player-detail-body').innerHTML=h;const modal=document.getElementById('player-detail');modal.classList.add('show');modal.setAttribute('aria-hidden','false');}
function closeDetail(){const m=document.getElementById('player-detail');m.classList.remove('show');m.setAttribute('aria-hidden','true');}
function downloadCsv(){if(!rows.length){notify("提出データがありません");return;}const lines=[["プレイヤーNo.","表示名","提出日時","正解数","回答数","正答率"]];rows.forEach(r=>lines.push([r.playerNo||"旧データ",r.name,r.receivedAt||r.sentAt,r.correct,r.total,r.rate]));const body=lines.map(row=>row.map(v=>'"'+String(v??"").replace(/"/g,'""')+'"').join(',')).join('\r\n');const b=new Blob(["\ufeff"+body],{type:"text/csv;charset=utf-8"}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=`skimaru_history_${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function clearAll(){if(!rows.length||!confirm("提出履歴をすべて削除しますか？")||!confirm("元に戻せません。本当に削除しますか？"))return;if(!(await ensureSession()))return;try{const endpoint=`${CLOUD.url}/rest/v1/${encodeURIComponent(CLOUD.table||"exam_results")}?id=not.is.null`;const r=await fetch(endpoint,{method:"DELETE",headers:{...authHeaders(session.access_token),Prefer:"return=minimal"}});if(!r.ok)throw new Error();rows=[];groups=[];setConnection();render();notify("削除しました");}catch(e){notify("削除できませんでした");}}
document.getElementById("login-btn").addEventListener("click",login);document.getElementById("manager-password").addEventListener("keydown",e=>{if(e.key==="Enter")login();});document.getElementById("logout").addEventListener("click",logout);document.getElementById("refresh").addEventListener("click",()=>loadRows());document.getElementById("csv-learners").addEventListener("click",downloadCsv);document.getElementById("clear").addEventListener("click",clearAll);document.getElementById("player-detail-close").addEventListener("click",closeDetail);document.getElementById("player-detail").addEventListener("click",e=>{if(e.target.id==="player-detail")closeDetail();});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeDetail();});
checkAuth();setInterval(()=>{if(authenticated)loadRows(true);},15000);
