"use strict";
(() => {
 let players=[],loading=false,confirmDialog=null;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 async function rpc(name,body={}){if(typeof ensureSession!=='function'||!(await ensureSession()))throw Error('開発者としてログインしてください。');const r=await fetch(`${CLOUD.url}/rest/v1/rpc/${name}`,{method:'POST',headers:authHeaders(session.access_token),body:JSON.stringify(body),cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok)throw Error(data.message||'取得できませんでした。');return data;}
 function panel(){let p=document.getElementById('registered-players');if(!p){p=document.createElement('section');p.id='registered-players';p.className='manager-section registered-panel';document.querySelector('.manager-pad')?.append(p);}return p;}
 function render(){const p=panel();if(!p)return;const site=document.getElementById('site-filter')?.value||'',list=players.filter(x=>!site||x.site===site);p.innerHTML=`<div class="registered-head"><div><h2>登録者の管理</h2><p>成績提出前の登録者も表示します。削除できるのは開発者だけです。</p></div><button type="button" class="btn-g" id="registered-refresh">一覧を更新</button></div><small>${list.length}人 / 全体 ${players.length}人</small><div class="registered-list">${list.map((x,i)=>`<div class="registered-item"><div><b>${esc(x.site)} ／ ${esc(x.name)}</b><small>${x.registered?'登録済み':'従来の提出データ'} ・ 提出 ${x.submissionCount}件</small><small>${esc(x.playerNo||'旧データ')} ${x.lastSubmittedAt?'／ 最終提出 '+esc(new Date(x.lastSubmittedAt).toLocaleString('ja-JP')):''}</small></div><button type="button" data-delete-member="${i}">登録・成績を削除</button></div>`).join('')||'<p class="registered-empty">この拠点の登録者はいません。</p>'}</div><p class="manager-empty-small">v13で登録した対象端末の登録と学習履歴は、次にオンラインでアプリを開いたときに消去されます。</p>`;p.querySelector('#registered-refresh').onclick=load;p.querySelectorAll('[data-delete-member]').forEach(b=>b.onclick=()=>openDelete(list[Number(b.dataset.deleteMember)]));}
 async function load(){if(loading||!authenticated)return;loading=true;const p=panel();try{const j=await rpc('skimaru_developer_players');if(!Array.isArray(j))throw Error('一覧を取得できませんでした。');players=j;render();}catch(e){if(p)p.innerHTML=`<h2>登録者の管理</h2><p role="alert">${esc(e.message.includes('developer_required')?'このアカウントは開発者権限がありません。':e.message)}</p><button type="button" class="btn-g" id="registered-retry">再試行</button>`;p?.querySelector('#registered-retry')?.addEventListener('click',load);}finally{loading=false;}}
 function close(){confirmDialog?.remove();confirmDialog=null;}
 function openDelete(person){close();const d=document.createElement('div');d.className='rollout-overlay';d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');d.setAttribute('aria-labelledby','delete-member-title');d.innerHTML=`<div class="rollout-dialog"><button type="button" class="rollout-close" id="delete-member-cancel">キャンセル</button><h2 id="delete-member-title">登録と成績を削除</h2><div class="registered-delete-details"><b>${esc(person.site)} ／ ${esc(person.name)}</b><p>プレイヤーNo. ${esc(person.playerNo||'旧データ')}<br>対象：登録情報、提出済み成績 ${person.submissionCount}件、個別メッセージ</p></div><p>削除は元に戻せません。v13登録済み端末内の履歴は次回オンライン接続時に消去されます。</p><label for="delete-member-name">確認のため、表示名「${esc(person.name)}」を入力してください。</label><input id="delete-member-name" class="registered-delete-name" autocomplete="off"><div class="registered-delete-error" id="delete-member-error" role="alert"></div><button type="button" class="rollout-primary registered-delete-confirm" id="delete-member-confirm" disabled>この登録者のデータを削除する</button></div>`;document.body.append(d);confirmDialog=d;const input=d.querySelector('input'),button=d.querySelector('#delete-member-confirm');d.querySelector('#delete-member-cancel').onclick=close;input.oninput=()=>button.disabled=input.value!==person.name;d.addEventListener('keydown',e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const els=[...d.querySelectorAll('button:not(:disabled),input')];if(e.shiftKey&&document.activeElement===els[0]){e.preventDefault();els.at(-1).focus();}else if(!e.shiftKey&&document.activeElement===els.at(-1)){e.preventDefault();els[0].focus();}}});button.onclick=async()=>{if(input.value!==person.name)return;button.disabled=true;button.textContent='削除中…';try{const result=await rpc('skimaru_delete_player',{p_player_key:person.key,p_expected_count:person.submissionCount,p_confirm_name:input.value});close();await loadRows(true);await load();notify(`対象者の登録と成績 ${result.deletedSubmissions}件を削除しました。`);}catch(e){d.querySelector('#delete-member-error').textContent=e.message.includes('submissions_changed')?'新しい提出がありました。キャンセルし、一覧を更新してから確認してください。':e.message.includes('developer_required')?'開発者権限がありません。':e.message.includes('name_confirmation')?'確認名が一致しません。':'削除できませんでした。通信とログインを確認してください。';button.disabled=false;button.textContent='この登録者のデータを削除する';}};input.focus();}
 const oldHide=hideLogin;hideLogin=function(){const r=oldHide.apply(this,arguments);load();return r;};const oldLogout=logout;logout=async function(){close();players=[];document.getElementById('registered-players')?.remove();return oldLogout.apply(this,arguments);};
 document.getElementById('site-filter')?.addEventListener('change',render);document.getElementById('refresh')?.addEventListener('click',load);if(authenticated)load();
})();
