"use strict";
(()=>{
const KEY='skimaru-grade1-v16',TYPES=['academic','practical'],read=(k,f={})=>{try{return JSON.parse(localStorage.getItem(k)||'null')||f;}catch{return f;}},empty=()=>({total:0,correct:0,seconds:0,cats:{}});
const initial={schema:1,stats:{academic:empty(),practical:empty()},questionStats:{},history:[],submitted:{academic:0,practical:0},pending:[],current:null,year:2025,branch:'A',examDate:''};
let s=read(KEY,initial);if(s.schema!==1)s=initial;
let screen='home',page=0,busy=false,lastTick=Date.now(),lastActivity=Date.now(),timer;
const main=document.getElementById('main'),DATA=window.SKIMARU_GRADE1_DATA,all=[],map=new Map();
Object.entries(DATA).forEach(([year,d])=>{all.push(...d.academic);d.tasks.forEach(t=>Object.entries(t.answers).forEach(([number,answer])=>all.push({id:t.id+'-'+number,year:+year,type:'practical',number:+number,task:t.id,title:t.title,branch:t.branch,category:t.category,answer,images:t.images,pages:t.pages,choices:t.choices})));});all.forEach(q=>map.set(q.id,q));
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=(c,t)=>t?Math.round(c/t*100):0,kind=t=>t==='academic'?'学科':'実技',min=n=>Math.round(n/60)+'分',rate=v=>pct(v.correct,v.total)+'%';
function save(){try{localStorage.setItem(KEY,JSON.stringify(s));return true;}catch{notice('端末に保存できません。空き容量を確認して、この画面を閉じずに成績を提出してください。');return false;}}
function notice(t){const el=document.getElementById('notice');el.textContent=t;clearTimeout(timer);timer=setTimeout(()=>el.textContent='',6500);}
function guard(){if(window.SKIMARU_MEMBER?.valid())return true;window.SKIMARU_MEMBER?.startRegistration();return false;}
function metrics(){const m={};TYPES.forEach(t=>m[t]={total:s.stats[t].total,correct:s.stats[t].correct,seconds:Math.round(s.stats[t].seconds),timeMeasured:true});return m;}
function show(view='home'){screen=view;render();window.scrollTo(0,0);}
function button(label,fn,cls=''){const b=document.createElement('button');b.textContent=label;b.className=cls;b.onclick=fn;return b;}
function bind(id,fn){document.getElementById(id)?.addEventListener('click',fn);}
function summary(){const a=s.stats.academic,p=s.stats.practical;return `<div class="stats"><div><b>${pct(a.correct+p.correct,a.total+p.total)}%</b><small>累計正答率</small></div><div><b>${a.total+p.total}</b><small>累計回答数</small></div><div><b>${min(a.seconds+p.seconds)}</b><small>記録学習時間</small></div></div>`;}
function render(){if(screen==='quiz'&&s.current)return quiz();if(screen==='result')return result();if(screen==='settings')return settings();home();}
function home(){
 const pending=TYPES.some(t=>s.stats[t].total>s.submitted[t]),date=s.examDate?new Date(s.examDate+'T00:00:00+09:00'):null,days=date?Math.max(0,Math.ceil((date-Date.now())/86400000)):null;
 main.innerHTML=`<div class="row"><span class="label">LEARNING QUEST / 1級</span><a href="./player.html">2級へ切り替える →</a></div><h1>今日も、保全力を<br>ひとつ伸ばそう。</h1>${summary()}${date?`<div class="card date-card"><span>試験日 ${esc(s.examDate)}<br><small>歯車から変更できます</small></span><b>あと ${days} 日</b></div>`:''}${s.current?'<div class="card"><h2>途中のチャレンジがあります</h2><div class="row"><button id="resume">続きから再開</button><button id="discard" class="secondary">終了してホームへ</button></div></div>':''}<div class="card"><h2>5問からレベルアップ</h2><div class="grid"><button id="five">学科 5問</button><button id="ten">学科 10問</button><button id="review" class="secondary">学科の苦手を復習</button><button id="practical-review" class="secondary">実技の苦手を復習</button></div><p class="muted">2022〜2025年度から出題。練習は1問ずつ答えを確認できます。</p></div><div class="card"><h2>年度別にチャレンジ</h2><div class="grid"><label>年度<select id="year">${Object.keys(DATA).map(y=>`<option ${+y===s.year?'selected':''}>${y}</option>`).join('')}</select></label><label>実技の選択課題<select id="branch"><option value="A" ${s.branch==='A'?'selected':''}>A / 加工・組立</option><option value="B" ${s.branch==='B'?'selected':''}>B / 装置産業</option></select></label></div><div class="grid"><button id="academic-exam">学科 100問</button><button id="practical-exam">実技 全課題</button></div><p class="muted">年度別の全問チャレンジは最後にまとめて採点。途中の回答も保存します。</p><details><summary>実技を課題ごとに練習</summary><div id="tasks" class="tasks"></div></details></div><div class="card"><h2>成果を共有しよう</h2>${pending?'<p class="warning">まだ提出していない1級の学習記録があります。</p>':'<p class="muted">提出すると1級・2級の端末データを自動バックアップします。</p>'}<button id="submit" ${busy?'disabled':''}>${busy?'提出中…':'1級の成績を提出する'}</button><p class="muted">管理者には学科・実技ごとの累計正答率、回答数、記録学習時間を共有します。復旧コードは歯車から控えてください。</p></div><div class="card"><h2>1級の学習記録</h2><p>学科 ${rate(s.stats.academic)} / ${s.stats.academic.total}問<br>実技 ${rate(s.stats.practical)} / ${s.stats.practical.total}問</p><div id="categories"></div><details><summary>最近のチャレンジ</summary>${s.history.slice(-20).reverse().map(h=>`<div class="history"><b>${esc(h.title)}</b>${h.correct}/${h.total}問 正解・${h.rate}% / ${min(h.elapsedSeconds)}<br><span class="muted">${new Date(h.completedAt).toLocaleString('ja-JP')}</span></div>`).join('')||'<p class="muted">まだ記録はありません</p>'}</details></div><p class="muted">収録：2022〜2025年度 学科400問・実技全課題（A/B両方）。解答は提供された正解表に基づきます。詳しい解説は未収録です。</p><div class="row"><a href="./player-guide.html">使い方</a><button class="secondary" data-open-install>ホーム画面に追加</button></div>`;
 bind('five',()=>start(shuffle(all.filter(q=>q.type==='academic')).slice(0,5),'practice','学科 5問チャレンジ'));bind('ten',()=>start(shuffle(all.filter(q=>q.type==='academic')).slice(0,10),'practice','学科 10問チャレンジ'));
 for(const [id,type]of [['review','academic'],['practical-review','practical']])bind(id,()=>{const qs=shuffle(all.filter(q=>q.type===type&&s.questionStats[q.id]?.lastWrong)).slice(0,10);qs.length?start(qs,'practice',kind(type)+' 苦手復習'):notice('苦手の記録はまだありません。');});
 bind('resume',()=>{if(guard())show('quiz');});bind('discard',()=>{if(confirm('途中のチャレンジを終了しますか？すでに答えを確認した練習の成績は残ります。')){s.current=null;save();show();}});
 const tasks=()=>{document.getElementById('tasks').replaceChildren(...DATA[s.year].tasks.filter(t=>!t.branch||t.branch===s.branch).map(t=>button(t.title,()=>start(all.filter(q=>q.task===t.id),'practice',`${s.year}年度 ${t.title}`))));};tasks();
 for(const id of ['year','branch'])document.getElementById(id).onchange=e=>{s[id]=id==='year'?+e.target.value:e.target.value;save();tasks();};
 bind('academic-exam',()=>start(DATA[s.year].academic,'exam',`${s.year}年度 学科100問`));bind('practical-exam',()=>start(all.filter(q=>q.year===s.year&&q.type==='practical'&&(!q.branch||q.branch===s.branch)),'exam',`${s.year}年度 実技（選択${s.branch}）`));bind('submit',submit);
 const cat=document.getElementById('categories');TYPES.forEach(t=>{const weak=Object.entries(s.stats[t].cats).filter(([,v])=>v.total).sort((a,b)=>pct(a[1].correct,a[1].total)-pct(b[1].correct,b[1].total)).slice(0,3);if(weak.length){const p=document.createElement('p');p.className='muted';p.textContent=kind(t)+' / '+weak.map(([name,v])=>name+' '+rate(v)).join('・');cat.append(p);}});
}
function shuffle(qs){qs=[...qs];for(let i=qs.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[qs[i],qs[j]]=[qs[j],qs[i]];}return qs;}
function start(qs,mode,title){if(!guard())return;if(s.current&&!confirm('途中のチャレンジを終了して新しく始めますか？答えを確認済みの練習成績は残ります。'))return;s.current={id:crypto.randomUUID(),ids:qs.map(q=>q.id),answers:{},recorded:[],index:0,mode,title,seconds:0,startedAt:new Date().toISOString()};page=0;lastActivity=lastTick=Date.now();save();show('quiz');}
function commit(q){const c=s.current;if(c.recorded.includes(q.id))return;const good=c.answers[q.id]===q.answer,v=s.stats[q.type];v.total++;v.correct+=+good;const cat=v.cats[q.category]||(v.cats[q.category]={total:0,correct:0});cat.total++;cat.correct+=+good;const r=s.questionStats[q.id]||(s.questionStats[q.id]={total:0,correct:0});r.total++;r.correct+=+good;r.lastWrong=!good;c.recorded.push(q.id);}
let sourcePath='';const viewer=window.SKIMARU_IMAGE_VIEWER.create({year:'1級',imagePath:()=>sourcePath});
function quiz(){const c=s.current,q=map.get(c.ids[c.index]);if(!q){s.current=null;save();show();return;}page=Math.min(page,q.images.length-1);const checked=c.recorded.includes(q.id),selected=c.answers[q.id];
 main.innerHTML=`<div class="row"><button id="pause" class="secondary">中断してホームへ</button><span class="muted">${esc(c.title)}</span></div><div class="progress"><span style="width:${(c.index+1)/c.ids.length*100}%"></span></div><p class="muted">${c.index+1} / ${c.ids.length}問 · ${q.year}年度 ${kind(q.type)} · 問題No. ${q.number}</p><div class="card"><h2>${q.type==='practical'?esc(q.title):'○か×で答えよう'}</h2><div class="question-layout"><div>${q.type==='academic'?`<p class="question">${esc(q.text)}</p>`:''}<img id="source" class="source" src="${q.images[page]}" alt="${q.year}年度 ${kind(q.type)} 問題の原文" tabindex="0"><p class="muted">タップで拡大。図・式・選択肢は原文で確認できます。</p>${q.images.length>1?`<div class="row pager"><button id="page-prev" class="secondary" ${page===0?'disabled':''}>前のページ</button><span>${page+1}/${q.images.length}（PDF ${q.pages[page]}頁）</span><button id="page-next" class="secondary" ${page===q.images.length-1?'disabled':''}>次のページ</button></div>`:''}</div><div><p>${q.type==='practical'?`<b>解答欄 ${q.number} の記号を選んでください</b><br><span class="muted">記号ボタンは課題内で使われる選択肢の一覧です。原文の該当する選択肢を確認してください。</span>`:'正しい文は○、誤っている文は×。'}</p><div class="choices">${q.choices.map(ch=>`<button data-choice="${ch}" aria-pressed="${ch===selected}" class="${ch===selected?'selected':''}" ${checked?'disabled':''}>${ch}</button>`).join('')}</div>${checked?`<div class="answer ${selected===q.answer?'':'wrong'}">${selected===q.answer?'正解！':'もう一度覚えよう'}<br>正解は ${q.answer}${selected?' / あなたの回答 '+esc(selected):' / 未回答'}</div><p class="muted">公式の正解表と原文を照らし合わせて復習しましょう。</p>`:''}${c.mode==='practice'&&!checked?'<button id="check">答えを確認する</button>':''}<div class="quiz-nav"><button id="prev" class="secondary" ${c.index===0?'disabled':''}>前の問題</button><button id="next">${c.index===c.ids.length-1?'結果を見る':'次の問題'}</button></div><p class="muted">${c.mode==='exam'?'最後にまとめて採点します。途中の回答は変更できます。':'答えを確認すると学習記録に反映します。'}</p><button id="finish" class="secondary">ここで終了・採点</button></div></div></div>`;
 main.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{if(!guard()||checked)return;c.answers[q.id]=b.dataset.choice;save();quiz();});
 bind('pause',()=>{save();show();});bind('check',()=>{if(!guard())return;if(!c.answers[q.id]){notice('回答を選んでください。');return;}commit(q);save();quiz();});
 bind('prev',()=>{c.index--;page=0;save();quiz();});bind('next',()=>{if(c.mode==='practice'&&!checked){notice('先に「答えを確認する」を押してください。');return;}if(c.index===c.ids.length-1)finish();else{c.index++;page=0;save();quiz();window.scrollTo(0,0);}});bind('finish',finish);
 bind('page-prev',()=>{page--;quiz();});bind('page-next',()=>{page++;quiz();});
 function zoom(){sourcePath=q.images[page];viewer.open(q.pages[page],document.getElementById('source'));document.getElementById('originalPageLabel').textContent=`1級 ${q.year}年度 / 原文 PDF ${q.pages[page]}頁`;document.getElementById('originalImage').alt=`1級 ${q.year}年度 原文`;}
 bind('source',zoom);document.getElementById('source').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();zoom();}};
}
function finish(){if(!guard()||!s.current)return;const c=s.current,missing=c.ids.filter(id=>!c.answers[id]).length;if(missing&&!confirm(`未回答が${missing}問あります。未回答は不正解として採点しますか？`))return;c.ids.forEach(id=>commit(map.get(id)));const qs=c.ids.map(id=>map.get(id)),correct=qs.filter(q=>c.answers[q.id]===q.answer).length;s.history.push({id:c.id,title:c.title,type:qs[0].type,year:qs.every(q=>q.year===qs[0].year)?qs[0].year:null,total:qs.length,correct,rate:pct(correct,qs.length),completedAt:new Date().toISOString(),elapsedSeconds:Math.round(c.seconds),answers:{...c.answers},ids:[...c.ids]});s.history=s.history.slice(-100);s.current=null;save();show('result');}
function result(){const h=s.history.at(-1);if(!h)return show();main.innerHTML=`<span class="label">QUEST COMPLETE / 1級</span><h1>${h.rate}% 正解！</h1><div class="card"><h2>${esc(h.title)}</h2><p>${h.correct}/${h.total}問 正解 · ${min(h.elapsedSeconds)}</p><p class="muted">累計記録に反映しました。成績を提出して管理者と共有しましょう。</p><div class="row"><button id="home">ホームへ</button><button id="submit" class="secondary">成績を提出</button></div></div><div class="card"><h2>間違えた問題を確認</h2><div id="mistakes"></div></div>`;bind('home',()=>show());bind('submit',submit);const mistakes=h.ids.filter(id=>h.answers[id]!==map.get(id).answer);document.getElementById('mistakes').replaceChildren(...mistakes.map(id=>{const q=map.get(id),b=button(`${q.year}年度 ${kind(q.type)} No.${q.number} / 正解 ${q.answer}`,()=>{sourcePath=q.images[0];viewer.open(q.pages[0],b);document.getElementById('originalPageLabel').textContent=`1級 ${q.year}年度 問題No.${q.number}`;},'secondary');return b;}));if(!mistakes.length)document.getElementById('mistakes').textContent='全問正解！この調子で続けよう。';}
function settings(){const p=read('skimaruData');main.innerHTML=`<h1>設定</h1><div class="card"><h2>登録情報</h2><p>${esc(p.site)} / ${esc(p.name)}<br><span class="muted">プレイヤーNo. ${esc(p.playerNo)}</span></p><button id="profile" class="secondary">拠点・名前を確認／変更</button><p class="muted">1級・2級で同じ登録情報を使用します。</p></div><div class="card"><h2>試験日</h2><label>あなたの受験日<input id="exam-date" type="date" value="${esc(s.examDate)}"></label><p class="muted">受験票の日付を設定してください。</p></div><div class="card"><h2>自動バックアップと復元</h2><p>成績を提出すると、1級・2級の学習記録をまとめて保存します。復元できるのは最後の提出時点です。</p><div class="row"><button id="recovery">復旧コードを控える</button><button id="restore" class="secondary">以前のデータを復元</button></div></div><button id="home" class="secondary">ホームへ戻る</button>`;bind('profile',()=>window.SKIMARU_MEMBER.edit());bind('recovery',()=>window.SKIMARU_BACKUP.showCode());bind('restore',()=>window.SKIMARU_BACKUP.restore());bind('home',()=>show());document.getElementById('exam-date').onchange=e=>{s.examDate=e.target.value;save();};}
async function submit(){if(busy||!guard())return;busy=true;if(screen==='home')home();try{if(!await window.SKIMARU_MEMBER.checkRegistration(true))throw Error('登録情報を確認してください。');const profile=read('skimaruData');for(const type of TYPES){const v=s.stats[type];if(v.total<=s.submitted[type]||s.pending.some(x=>x.raw_result.examType===type&&x.total_questions===v.total))continue;const id=crypto.randomUUID(),sentAt=new Date().toISOString(),raw={id,grade:1,examType:type,playerNo:profile.playerNo,name:profile.name,site:profile.site,total:v.total,correct:v.correct,cats:v.cats,studyMetricsV12:metrics(),sentAt,elapsedSeconds:Math.round(v.seconds),pastYearHistory:s.history.filter(h=>h.type===type).slice(-40).map(({answers,ids,...h})=>({...h,kind:type==='academic'?'gakka':'jitugi'})),alerts:all.filter(q=>q.type===type&&s.questionStats[q.id]?.lastWrong).slice(0,50).map(q=>({id:q.id,year:q.year,number:q.number,category:q.category,answer:q.answer,text:q.text||q.title}))};s.pending.push({submission_id:id,player_no:profile.playerNo,user_name:profile.name,total_questions:v.total,correct_count:v.correct,elapsed_seconds:Math.min(31536000,Math.round(v.seconds)),category_results:v.cats,submitted_at:sentAt,raw_result:raw});}save();for(const row of [...s.pending]){await window.SKIMARU_BACKUP.submit(row);const type=row.raw_result.examType;s.submitted[type]=Math.max(s.submitted[type],row.total_questions);s.pending=s.pending.filter(r=>r.submission_id!==row.submission_id);save();}notice('1級の成績提出と自動バックアップが完了しました。');}catch(e){notice(e.message||'提出できませんでした。記録は端末に残っています。通信が戻ってから再提出してください。');}finally{busy=false;if(screen==='home')home();}}
document.getElementById('settings').onclick=()=>show('settings');for(const event of ['pointerdown','keydown'])document.addEventListener(event,()=>lastActivity=Date.now(),{passive:true});
setInterval(()=>{const now=Date.now(),delta=Math.min(5,(now-lastTick)/1000);lastTick=now;if(screen==='quiz'&&s.current&&!document.hidden&&now-lastActivity<120000){s.current.seconds+=delta;s.stats[map.get(s.current.ids[s.current.index]).type].seconds+=delta;save();}},1000);
window.addEventListener('online',()=>{if(s.pending.length)submit();});window.addEventListener('skimaru-profile',()=>{if(screen==='settings')settings();});window.addEventListener('beforeunload',save);
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});show();document.addEventListener('click',e=>{if(e.target.closest('[data-open-install]'))window.SKIMARU_ROLLOUT.install();});
})();
