"use strict";
(() => {
  const SITES=["四日市","石岡","足利","水戸","真岡","門真","北九州"],KEY="skimaruData",LEDGER="skimaru-submitted-v11",QUEUE="skimaru-pending-submissions-v1";
  const read=(k,f={})=>{try{return JSON.parse(localStorage.getItem(k)||"null")||f;}catch{return f;}};
  const write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  let profile=read(KEY),busy=false;
  if(profile.name?.trim()&&!profile.site){profile.site="四日市";try{write(KEY,profile);}catch{}}
  const valid=()=>!!read(KEY).name?.trim()&&SITES.includes(read(KEY).site);
  const style=document.createElement("style");style.textContent=`
    .member-gate{position:fixed;inset:0;z-index:2000000;background:#172431dc;display:grid;place-items:center;padding:max(20px,env(safe-area-inset-top)) 20px max(20px,env(safe-area-inset-bottom));overflow:auto}
    .member-card{background:#fff;color:#172431;padding:26px;border-radius:20px;width:min(420px,100%);max-height:100%;overflow:auto;box-sizing:border-box}.member-card h2{margin:0 0 10px}.member-card p{font-size:14px;line-height:1.6}.member-card label{display:block;margin:18px 0 8px;font-weight:700}.member-card select,.member-card input{width:100%;box-sizing:border-box;font-size:16px;padding:13px;border:1px solid #98aaa2;border-radius:9px;background:white;color:#172431}.member-card button,.member-bar button{border:0;border-radius:9px;background:#176844;color:white;padding:12px 16px;font-weight:700;cursor:pointer}.member-card button{width:100%;margin-top:22px}.member-error{color:#a32b20;font-size:14px}.member-bar{background:#f5faf7;border:1px solid #a6c3b5;border-radius:12px;padding:12px;margin:12px auto;width:min(880px,calc(100% - 24px));box-sizing:border-box;color:#172431;font-size:14px;line-height:1.5}.member-bar header{display:flex;justify-content:space-between;align-items:center;gap:10px}.member-bar header button{background:#e1ece5;color:#174831;padding:6px 10px}.member-alert{margin-top:10px;padding:12px;background:#fff1d6;border-radius:9px}.member-alert button{margin-top:8px}.member-alert[hidden]{display:none}
  `;document.head.append(style);
  function sync(){profile=read(KEY);window.dispatchEvent(new CustomEvent("skimaru-profile",{detail:profile}));refresh();}
  function register(edit=false){
    if(document.querySelector(".member-gate"))return;
    const gate=document.createElement("div");gate.className="member-gate";gate.setAttribute("role","dialog");gate.setAttribute("aria-modal","true");gate.setAttribute("aria-labelledby","member-title");
    gate.innerHTML='<form class="member-card"><h2 id="member-title">拠点・名前を登録</h2><p>成績をあなたの拠点にまとめます。登録してからプレイしてください。</p><label for="member-site">拠点</label><select id="member-site" required><option value="">拠点を選択</option></select><label for="member-name">名前</label><input id="member-name" maxlength="20" autocomplete="name" required placeholder="名前を入力"><div class="member-error" role="alert"></div><button type="submit">'+(edit?'登録内容を保存':'登録してプレイ')+'</button></form>';
    SITES.forEach(s=>gate.querySelector("select").add(new Option(s,s)));gate.querySelector("select").value=read(KEY).site||"";gate.querySelector("input").value=read(KEY).name||"";
    const frozen=[...document.body.children].filter(e=>!e.inert&&e.tagName!=="SCRIPT"&&e.tagName!=="STYLE");frozen.forEach(e=>e.inert=true);document.body.append(gate);
    gate.querySelector("form").onsubmit=e=>{e.preventDefault();const name=gate.querySelector("input").value.trim(),site=gate.querySelector("select").value;if(!name||!SITES.includes(site)){gate.querySelector(".member-error").textContent="拠点と名前を入力してください。";return;}try{const p=read(KEY);p.name=name;p.site=site;p.playerNo=p.playerNo||"P-"+crypto.randomUUID().replace(/-/g,"").slice(0,8).toUpperCase();write(KEY,p);}catch{gate.querySelector(".member-error").textContent="登録内容を保存できません。ブラウザの保存設定を確認してください。";return;}frozen.forEach(e=>e.inert=false);gate.remove();sync();};
    gate.addEventListener("keydown",e=>{if(e.key!=="Tab")return;const els=[...gate.querySelectorAll("select,input,button")],first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});gate.querySelector("select").focus();
  }
  const nativeFetch=window.fetch.bind(window);
  window.fetch=async(input,init)=>{
    const url=typeof input==="string"?input:input?.url;
    let row;
    if(init?.method==="POST"&&url?.includes("/rest/v1/")&&!url.includes("/rpc/")){
      try{row=JSON.parse(init.body);if(row.raw_result){row.raw_result.site=row.raw_result.site||read(KEY).site||"四日市";if(row.raw_result.examType!=="practical"){row.raw_result.academicSnapshot??=Number(row.raw_result.total)||0;row.raw_result.progressEpoch??=0;}init={...init,body:JSON.stringify(row)};}}catch{}
    }
    const res=await nativeFetch(input,init);
    if(res.ok&&row?.raw_result){const r=row.raw_result,l=read(LEDGER);if(r.examType==="practical"){l.practical=[...new Set([...(l.practical||[]),...(r.historyIds||[])])];}else if((r.progressEpoch||0)===(read(KEY).progressEpoch||0)){l.academic=Math.max(Number(l.academic)||0,Number(r.academicSnapshot??r.total)||0);l.academicHistory=[...new Set([...(l.academicHistory||[]),...(r.historyIds||[])])];}write(LEDGER,l);refresh();}
    return res;
  };
  function outstanding(){const p=read(KEY),l=read(LEDGER),q=read(QUEUE,[]);const academic=Math.max(0,(Number(p.total)||0)-Math.max(Number(l.academic)||0,...q.filter(r=>r.examType!=="practical"&&(r.progressEpoch||0)===(p.progressEpoch||0)).map(r=>Number(r.academicSnapshot??r.total)||0)));const covered=new Set([...(l.practical||[]),...q.flatMap(r=>r.historyIds||[])]);const hist=read("skimaruExamHistory_v1",[]).filter(r=>r.kind==="jitugi"&&r.completedAt&&!covered.has(r.id));const aCovered=new Set([...(l.academicHistory||[]),...q.filter(r=>r.examType!=="practical").flatMap(r=>r.historyIds||[])]),academicHist=read("skimaruExamHistory_v1",[]).filter(r=>r.kind==="gakka"&&r.completedAt&&!aCovered.has(r.id));return {academic,academicHist,hist,pending:q.length};}
  let bar;
  function setText(el,value){if(el.textContent!==value)el.textContent=value;}
  function refresh(){if(!bar)return;const p=read(KEY);setText(bar.querySelector(".member-identity"),`${p.site||"未登録"} ／ ${p.name||"名前未登録"}`);const {academic,academicHist,hist,pending}=outstanding(),box=bar.querySelector(".member-alert");box.hidden=!academic&&!academicHist.length&&!hist.length&&!pending;const parts=[];if(academic)parts.push(`学科 ${academic}問分`);if(academicHist.length)parts.push(`学科過去問 ${academicHist.length}回分`);if(hist.length)parts.push(`実技 ${hist.length}回分`);setText(box.querySelector("span"),parts.length?`未提出の成績があります（${parts.join("・")}）。成績を提出してください。${pending?` 送信待ち ${pending}件。オンラインで再送します。`:""}`:`送信待ち ${pending}件。通信が戻ると再送します。`);box.querySelector("button").hidden=!parts.length;}
  async function submit(){if(busy)return;if(!valid()){register();return;}const {academic,academicHist,hist}=outstanding();if(academic&&typeof window.showSend==="function"){window.showSend();return;}if(academic&&!hist.length&&!academicHist.length){location.href="./player.html#submit";return;}const examType=hist.length?"practical":"academic",history=hist.length?hist:academicHist;if(!history.length)return;busy=true;const btn=bar.querySelector(".member-alert button");btn.disabled=true;btn.textContent="提出中…";
    const p=read(KEY),sentAt=new Date().toISOString(),total=history.reduce((s,r)=>s+r.total,0),correct=history.reduce((s,r)=>s+r.correct,0);const record={id:crypto.randomUUID(),playerNo:p.playerNo,name:p.name,site:p.site,examType,total,correct,academicSnapshot:0,progressEpoch:p.progressEpoch||0,historyIds:history.map(r=>r.id),pastYearHistory:history,sentAt,cats:{},alerts:[]};
    const c=window.SKIMARU_SUPABASE||{},row={submission_id:record.id,player_no:p.playerNo,user_name:p.name,score:correct,total_questions:total,correct_count:correct,correct_rate:Math.round(correct/total*100),elapsed_seconds:0,exam_version:"11.0",submitted_at:sentAt,streak:0,mastered_count:0,wrong_count:total-correct,category_results:{},weak_questions:[],raw_result:record};
    try{if(!c.url)throw Error();const r=await fetch(`${c.url}/rest/v1/${encodeURIComponent(c.table||"exam_results")}`,{method:"POST",headers:{apikey:c.publishableKey,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify(row)});if(!r.ok)throw Error();alert((examType==="practical"?"実技":"学科過去問")+"の成績を提出しました。");}catch{try{const q=read(QUEUE,[]);q.push(record);write(QUEUE,q);alert("通信できないため成績を保存しました。オンラインで再送します。");}catch{alert("保存できませんでした。通信が戻ってからもう一度提出してください。");}}finally{busy=false;btn.disabled=false;btn.textContent="成績提出へ";refresh();}
  }
  async function retry(){if(busy||typeof window.retryPendingSubmissions==="function")return;const q=read(QUEUE,[]),c=window.SKIMARU_SUPABASE||{};if(!q.length||!c.url)return;busy=true;for(const record of q){try{const t=record.total||0,n=record.correct||0,r=await fetch(`${c.url}/rest/v1/${encodeURIComponent(c.table||"exam_results")}`,{method:"POST",headers:{apikey:c.publishableKey,"Content-Type":"application/json",Prefer:"return=minimal"},body:JSON.stringify({submission_id:record.id,player_no:record.playerNo,user_name:record.name,score:n,total_questions:t,correct_count:n,correct_rate:t?Math.round(n/t*100):0,elapsed_seconds:0,exam_version:"11.0",submitted_at:record.sentAt,streak:record.streak||0,mastered_count:record.mastered||0,wrong_count:record.wrongCount||0,category_results:record.cats||{},weak_questions:record.alerts||[],raw_result:record})});if(r.ok)write(QUEUE,read(QUEUE,[]).filter(x=>x.id!==record.id));}catch{break;}}busy=false;refresh();}
  window.SKIMARU_MEMBER={sites:SITES,edit:()=>register(true),refresh,outstanding};
  function boot(){bar=document.createElement("div");bar.className="member-bar";bar.innerHTML='<header><b class="member-identity"></b><button type="button">登録変更</button></header><div class="member-alert" role="status" aria-live="polite" hidden><span></span><br><button type="button">成績提出へ</button></div>';const home=document.querySelector("#sc-home .pad,#pt-home .pad,.wrap,main")||document.body;home.prepend(bar);bar.querySelector("header button").onclick=()=>register(true);bar.querySelector(".member-alert button").onclick=submit;sync();if(!valid())register();setInterval(refresh,2000);retry();if(location.hash==="#submit"&&valid()&&typeof window.showSend==="function")window.showSend();}
  document.readyState==="loading"?document.addEventListener("DOMContentLoaded",boot):boot();window.addEventListener("online",retry);window.addEventListener("storage",()=>{sync();if(!valid())register();});
})();
