"use strict";(()=>{
const $=id=>document.getElementById(id),early=window.SKIMARU_EARLY_OFFICIAL||{};
const specs=[{year:2022,kind:'gakka',total:100,key:'skimaruEarly_2022_gakka_v1'},{year:2022,kind:'jitugi',total:76,key:'skimaruEarly_2022_jitugi_v1'},{year:2023,kind:'gakka',total:100,key:'skimaruEarly_2023_gakka_v1'},{year:2023,kind:'jitugi',total:78,key:'skimaruEarly_2023_jitugi_v1'},{year:2024,kind:'jitugi',total:74,key:'skimaruPractical2024V750'},{year:2025,kind:'jitugi',total:72,key:'skimaruPractical2025V600'}];
const defs={2024:[[1,8,[11,12]],[9,13,[14]],[14,20,[15,16]],[21,29,[19,20]],[30,33,[21]],[34,41,[23]],[42,51,[25,26]],[52,55,[27]],[56,59,[28]],[60,66,[29,30]],[67,74,[31,32]]],2025:[[1,6,[12,13]],[7,14,[14,15]],[15,21,[16,17]],[22,30,[18]],[31,41,[20,21]],[42,49,[22]],[50,57,[24,25]],[58,59,[26]],[60,61,[27]],[62,63,[28]],[64,72,[30]]]};
function load(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch{return null}}
function taskData(spec,n,branch){if(spec.year<2024)return null;const tasks=spec.year===2024?window.SKIMARU_2024_OFFICIAL_TASKS:window.SKIMARU_2025_OFFICIAL_TASKS;if(!tasks)return null;return tasks.find(t=>(!t.choiceBranch||t.choiceBranch===branch)&&t.blanks?.some(b=>Number(String(b.id).replace('q',''))===n))?.blanks.find(b=>Number(String(b.id).replace('q',''))===n)}
function keyFor(spec,n,branch){if(spec.year<2024)return early[spec.year]?.[spec.kind]?.[n];return taskData(spec,n,branch)?.answer}
function pickedFor(spec,a,n){return spec.year<2024?a[n]:a[n]?.picked}
function wrongFor(spec){const state=load(spec.key);if(!state)return [];const a=state.answers||{};const count=Array.from({length:spec.total},(_,i)=>i+1).filter(n=>a[n]!==undefined&&a[n]!==null).length;const complete=(spec.year<2024?state.finished:state.completedAt)&&count===spec.total;if(!complete)return [];const wrong=[];for(let n=1;n<=spec.total;n++){const correct=keyFor(spec,n,state.branch);if(correct===undefined)continue;if(pickedFor(spec,a,n)!==correct)wrong.push({n,branch:state.branch,correct})}return wrong}
function pagesFor(spec,n,branch){if(spec.year<2024){const task=early[spec.year]?.tasks?.find(t=>n>=t.start&&n<=t.end);if(spec.kind==='gakka'){const starts=spec.year===2022?[1,15,31,50,67,87,98]:[1,13,32,50,63,75,89];let page=2;for(let i=0;i<starts.length;i++)if(n>=starts[i])page=i+2;return [page]}return task?.branch?(task.branch[branch]||[]):(task?.pages||[])}const groups=defs[spec.year]||[];const g=groups.find(([a,b])=>n>=a&&n<=b);if(!g)return [];if(spec.year===2024&&n>=14&&n<=20)return branch==='B'?[17,18]:[15,16];if(spec.year===2025&&n>=64)return [branch==='B'?31:30];return g[2]}
let session=null,position=0,answers={};const opts=$('source');
function refresh(){opts.replaceChildren();let count=0;for(const spec of specs){const wrong=wrongFor(spec);if(!wrong.length)continue;const o=document.createElement('option');o.value=spec.key;o.textContent=`${spec.year}年度 ${spec.kind==='gakka'?'学科':'実技'}（間違い ${wrong.length}問）`;opts.append(o);count+=wrong.length}const ready=opts.options.length>0;$('all').disabled=!ready;$('ten').disabled=!ready;$('available').textContent=ready?`復習可能な問題：合計${count}問。年度・科目を選択してください。`:'採点済みの試験に間違えた問題がありません。まず通常の試験を最後まで解いて採点してください。'}
function start(ten){grading=false;const spec=specs.find(s=>s.key===opts.value);if(!spec)return;let questions=wrongFor(spec);if(ten){for(let i=questions.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[questions[i],questions[j]]=[questions[j],questions[i]]}questions=questions.slice(0,10)}session={spec,questions};position=0;answers={};$('setup').classList.add('hidden');$('results').classList.add('hidden');$('exam').classList.remove('hidden');render()}
function render(){const {spec,questions}=session,q=questions[position];$('progressText').textContent=`${position+1} / ${questions.length}問・回答済み ${Object.keys(answers).length}問`;$('progressBar').style.width=(Object.keys(answers).length/questions.length*100)+'%';$('questionTitle').textContent=`${spec.year}年度 ${spec.kind==='gakka'?'学科':'実技'}・問題${q.n}${q.branch?'（選択'+q.branch+'）':''}`;const host=$('pages');host.replaceChildren();for(const p of pagesFor(spec,q.n,q.branch)){const section=document.createElement('section');const label=document.createElement('p');label.className='muted';label.textContent=`原本 PDF ${spec.year<2024?p:p-(spec.year===2024?3:4)}ページ`;const img=document.createElement('img');img.loading='lazy';img.decoding='async';img.alt=label.textContent;img.onerror=()=>{const warning=document.createElement('p');warning.className='muted';warning.textContent='原本画像を読み込めません。通信状況を確認して再読み込みしてください。';section.append(warning)};img.src=spec.year<2024?`./original_${spec.year}_${spec.kind}_p${p}.jpg`:`./official_${spec.year}_p${p}.png`;section.append(label,img);host.append(section)}const choice=$('choices');choice.replaceChildren();let labels;if(spec.year<2024)labels=spec.kind==='gakka'?['○','×']:(spec.year===2022?'アイウエオカキクケコサシス':'アイウエオカキクケコサシ').split('');else labels=taskData(spec,q.n,q.branch)?.choices||[];labels.forEach((value,i)=>{const b=document.createElement('button');b.textContent=value;b.className=answers[q.n]=== (spec.year<2024?value:i)?'chosen':'';b.setAttribute('aria-pressed',String(Boolean(b.className)));b.onclick=()=>{answers[q.n]=spec.year<2024?value:i;renderChoices()};choice.append(b)});$('prev').disabled=position===0;$('next').textContent=position===questions.length-1?'回答状況を確認':'次へ';$('grade').classList.toggle('hidden',position!==questions.length-1)}
function renderChoices(){const {spec,questions}=session,q=questions[position];Array.from($('choices').children).forEach((b,i)=>{const val=spec.year<2024?b.textContent:i;b.classList.toggle('chosen',answers[q.n]===val);b.setAttribute('aria-pressed',String(answers[q.n]===val))});$('progressText').textContent=`${position+1} / ${questions.length}問・回答済み ${Object.keys(answers).length}問`;$('progressBar').style.width=(Object.keys(answers).length/questions.length*100)+'%'}
let grading=false;function grade(){if(grading)return;const missing=session.questions.find(q=>answers[q.n]===undefined);if(missing){position=session.questions.indexOf(missing);alert('未回答の問題があります。全問回答後に採点します。');render();return}if(!confirm('すべての回答を確定し、採点しますか？'))return;grading=true;const {spec,questions}=session;let good=0;const host=$('resultRows');host.replaceChildren();for(const q of questions){const ok=answers[q.n]===q.correct;if(ok)good++;const row=document.createElement('div');row.className='result';const title=document.createElement('strong');title.textContent=`問題${q.n}　${ok?'○ 正解':'× 不正解'}`;title.className=ok?'good':'bad';const detail=document.createElement('p');const d=taskData(spec,q.n,q.branch);const correct=spec.year<2024?q.correct:d?.choices?.[q.correct]||String(q.correct);const picked=spec.year<2024?answers[q.n]:d?.choices?.[answers[q.n]]||String(answers[q.n]);detail.textContent=`あなた：${picked} ／ 正解：${correct}`;row.append(title,detail);host.append(row)}$('score').textContent=`${good} / ${questions.length}問（${Math.round(good/questions.length*100)}%）`;$('exam').classList.add('hidden');$('results').classList.remove('hidden');const key='skimaruReviewHistory_v1';let history=load(key);if(!Array.isArray(history))history=[];history.push({year:spec.year,kind:spec.kind,total:questions.length,correct:good,at:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(history));window.scrollTo(0,0)}
$('all').onclick=()=>start(false);$('ten').onclick=()=>start(true);$('prev').onclick=()=>{if(position>0){position--;render();window.scrollTo(0,0)}};$('next').onclick=()=>{if(position<session.questions.length-1){position++;render();window.scrollTo(0,0)}else grade()};$('grade').onclick=grade;$('again').onclick=()=>{$('results').classList.add('hidden');$('setup').classList.remove('hidden');refresh()};$('back').onclick=()=>location.href='./dashboard.html';refresh();
})();