"use strict";
(() => {
 if(window.SKIMARU_ROLLOUT)return;
 let promptEvent=null,dialog=null,previousFocus=null;
 const standalone=()=>matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
 const ios=()=>/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
 const android=()=>/Android/.test(navigator.userAgent);
 function guideHTML(mode){if(mode==='manager')return `<h2 id="rollout-title">マネージャーの使い方</h2><ol><li><b>「マネージャー」→「管理者」</b>を選び、共有されたパスワードで開きます。</li><li><b>拠点で絞り込み</b>、学科・実技・総合を切り替えて確認します。</li><li><b>正解率・回答数・学習時間</b>を比べ、回答の少ない人や苦手分野への声掛けに使います。</li><li>「最新」は直近の提出結果、「比較」は最新提出時点の累計です。未提出分は表示されません。</li></ol><p>学習時間はv12以降の計測分です。旧データの「未計測」は0分とは異なります。</p><p>管理者は閲覧用です。登録者データの削除・設定変更は開発者が行います。</p><a href="./manager-guide.html">配布用の簡単ガイドを開く</a>`;return `<h2 id="rollout-title">プレイヤーの使い方</h2><ol><li><b>拠点と名前を登録</b>します。初回のみインターネット接続が必要です。</li><li><b>「サクッと5問」</b>なら全科目から5問。科目別学科・実技も選べます。</li><li><b>学科</b>は自信度を選んで○×回答。<b>実技</b>は全問回答後にまとめて採点します。</li><li>学習が終わったら<b>「成績提出」</b>。未提出の案内が出たら提出してください。</li></ol><p>拠点・名前の変更とバックアップは歯車から行います。できるだけ同じ端末・同じブラウザで利用してください。</p><p>機種やOSによって、ブラウザとホーム画面アプリの保存領域が別になる場合があります。ホーム画面へ追加後は、そのアイコンから登録・学習すると確実です。</p><a href="./player-guide.html">配布用の簡単ガイドを開く</a>`;}
 function installHTML(){if(standalone())return `<h2 id="rollout-title">ホーム画面から利用中です</h2><p>次回もこのアイコンから開いてください。</p>`;if(ios())return `<h2 id="rollout-title">iPhoneでホーム画面に追加</h2><ol><li>このページを<b>Safari</b>で開きます。</li><li>画面の<b>共有ボタン（四角から上向きの矢印）</b>をタップします。共有は「…」メニュー内にある場合もあります。</li><li><b>「ホーム画面に追加」</b>を選びます。見つからない場合は共有メニューを下へスクロールし「アクションを編集」を確認します。</li><li>表示される場合は<b>「Webアプリとして開く」</b>をオンにし、<b>「追加」</b>をタップします。</li></ol><p>追加後はホーム画面の「スキマル保全士」から開いてください。</p>`;if(android())return `<h2 id="rollout-title">Androidでホーム画面に追加</h2>${promptEvent?'<button type="button" class="rollout-primary" id="rollout-native-install">この端末に追加</button>':''}<ol><li>このページを<b>Chrome</b>で開きます。</li><li>右上の<b>「︙」</b>メニューから<b>「アプリをインストール」または「ホーム画面に追加」</b>を選びます。</li><li><b>「インストール」または「追加」</b>をタップします。</li></ol><p>表示名は端末・ブラウザによって異なります。</p>`;return `<h2 id="rollout-title">ホーム画面に追加</h2><p>iPhoneはSafariの共有メニューから、AndroidはChromeの「︙」メニューから追加できます。</p><button type="button" class="rollout-primary" id="rollout-iphone">iPhoneの手順</button><button type="button" class="rollout-secondary" id="rollout-android">Androidの手順</button>${promptEvent?'<button type="button" class="rollout-primary" id="rollout-native-install">この端末に追加</button>':''}`;}
 function close(){if(!dialog)return;const d=dialog;dialog=null;d.remove();previousFocus?.focus?.();}
 function open(html){close();previousFocus=document.activeElement;const d=document.createElement('div');d.className='rollout-overlay';d.setAttribute('role','dialog');d.setAttribute('aria-modal','true');d.setAttribute('aria-labelledby','rollout-title');d.innerHTML=`<div class="rollout-dialog"><button type="button" class="rollout-close" aria-label="案内を閉じる">閉じる</button>${html}</div>`;document.body.append(d);dialog=d;d.querySelector('.rollout-close').onclick=close;d.addEventListener('keydown',e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const els=[...d.querySelectorAll('button,a')],a=els[0],b=els.at(-1);if(e.shiftKey&&document.activeElement===a){e.preventDefault();b.focus();}else if(!e.shiftKey&&document.activeElement===b){e.preventDefault();a.focus();}}});d.querySelector('#rollout-native-install')?.addEventListener('click',async()=>{const event=promptEvent;if(!event)return;promptEvent=null;await event.prompt();const choice=await event.userChoice;if(choice.outcome==='accepted')close();else install();});d.querySelector('#rollout-iphone')?.addEventListener('click',()=>open(`<h2 id="rollout-title">iPhoneの手順</h2><ol><li>Safariで開く</li><li>共有ボタンをタップ</li><li>「ホーム画面に追加」</li><li>「追加」をタップ</li></ol>`));d.querySelector('#rollout-android')?.addEventListener('click',()=>open(`<h2 id="rollout-title">Androidの手順</h2><ol><li>Chromeで開く</li><li>右上「︙」をタップ</li><li>「アプリをインストール」または「ホーム画面に追加」</li><li>「追加」をタップ</li></ol>`));d.querySelector('.rollout-close').focus();}
 function install(){open(installHTML());}
 function welcome(){open(`<h2 id="rollout-title">登録できました</h2><p>学科・実技の問題を選んではじめましょう。学習後は「成績提出」を忘れずに。</p>${standalone()?'':`<button type="button" class="rollout-primary" id="welcome-install">ホーム画面に追加する</button><p class="rollout-muted">次回からアイコン1つで開けます。</p>`}`);dialog.querySelector('#welcome-install')?.addEventListener('click',install);}
 window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();promptEvent=e;});window.addEventListener('appinstalled',()=>{promptEvent=null;document.querySelectorAll('[data-rollout-install]').forEach(e=>e.hidden=true);close();});
 window.SKIMARU_ROLLOUT={guide:mode=>open(guideHTML(mode)),install,welcome};
 function boot(){if(!document.querySelector('link[href*="rollout.css"]')){const c=document.createElement('link');c.rel='stylesheet';c.href='./rollout.css?v=14';document.head.append(c);}if(!document.querySelector('link[rel="manifest"]')){const m=document.createElement('link');m.rel='manifest';m.href='./manifest.webmanifest';document.head.append(m);}if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
 const manager=/^(admin|viewer)\.html$/.test(location.pathname.split('/').pop());const home=document.querySelector('#sc-home .pad,.pad.years,.manager-pad,.rollout-portal-actions,.wrap');if(home&&!document.querySelector('.rollout-tools')){const tools=document.createElement('div');tools.className='rollout-tools';tools.innerHTML=`<button type="button" data-rollout-guide>${manager?'マネージャー':'プレイヤー'}の使い方</button><button type="button" data-rollout-install ${standalone()?'hidden':''}>ホーム画面に追加</button>`;home.append(tools);const iconHelp=document.createElement('button');iconHelp.type='button';iconHelp.textContent='アイコンの更新方法';iconHelp.onclick=()=>open('<h2 id="rollout-title">新しいアイコンにする</h2><ol><li>今のアイコンから開き、歯車の「学習履歴をバックアップ」でファイルを保存します。</li><li>更新後のアプリをSafari / Chromeで開き、ホーム画面に追加します。</li><li>新しいアイコンから開いて、登録・成績を確認します。データが引き継がれない場合は歯車からバックアップを復元します。</li><li>新しいアイコンと成績を確認してから、古いアイコンを整理します。</li></ol><p>OSにより反映まで時間がかかる場合があります。先にバックアップを保存してください。</p>');tools.append(iconHelp);tools.querySelector('[data-rollout-guide]').onclick=()=>window.SKIMARU_ROLLOUT.guide(manager?'manager':'player');tools.querySelector('[data-rollout-install]').onclick=install;}
 if(manager){const share=document.createElement('a');share.className='rollout-qr-link';share.textContent='配布用QRを開く';share.href='./share-qr.html';document.querySelector('.rollout-tools')?.append(share);}

 document.querySelectorAll('[data-open-guide]').forEach(b=>b.onclick=()=>window.SKIMARU_ROLLOUT.guide(b.dataset.openGuide));document.querySelectorAll('[data-open-install]').forEach(b=>b.onclick=install);
 }
 document.readyState==='loading'?document.addEventListener('DOMContentLoaded',boot):boot();
})();
