"use strict";
(() => {
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const time=s=>s==null?'未計測':s<60?`${s}秒`:`${Math.floor(s/3600)?Math.floor(s/3600)+'時間 ':''}${Math.floor(s%3600/60)}分`;
 const raw=r=>r.raw||{};
 const at=r=>r.at||r.receivedAt||r.sentAt||'';
 function single(rows,type){const list=rows.filter(r=>r.examType===type).sort((a,b)=>new Date(at(a))-new Date(at(b)));const measured=[...list].reverse().find(r=>raw(r).studyMetricsV12?.[type]);if(measured){const m=raw(measured).studyMetricsV12[type];return {...m,seconds:m.timeMeasured?m.seconds:null};}
 const hs=new Map();list.forEach(r=>(raw(r).pastYearHistory||[]).forEach(h=>{if(h.id&&h.kind===(type==='academic'?'gakka':'jitugi'))hs.set(h.id,h);}));const core=type==='academic'?[...list].reverse().find(r=>raw(r).source==='player'||raw(r).academicSnapshot>0):null;let total=(core?.total||0)+[...hs.values()].reduce((s,h)=>s+(Number(h.total)||0),0),correct=(core?.correct||0)+[...hs.values()].reduce((s,h)=>s+(Number(h.correct)||0),0);if(!total&&list.length){const r=list.at(-1);total=r.total;correct=r.correct;}return {total,correct,seconds:null};}
 function metrics(person,mode){const list=person.rows||person.history||[],types=mode==='combined'?['academic','practical']:[mode];const ms=types.map(t=>single(list,t)),total=ms.reduce((s,m)=>s+m.total,0),correct=ms.reduce((s,m)=>s+m.correct,0),timed=ms.filter(m=>m.seconds!==null);return {total,correct,rate:total?Math.round(correct/total*100):null,seconds:timed.length?timed.reduce((s,m)=>s+m.seconds,0):null,partial:timed.length>0&&timed.length<ms.filter(m=>m.total>0).length};}
 let sort='rate';
 function html(people,mode){if(!people.length)return '';const ps=people.map(p=>({p,m:metrics(p,mode)})).sort((a,b)=>(b.m[sort]??-1)-(a.m[sort]??-1));const sites=[...new Set(ps.map(x=>x.p.site||'四日市'))].map(site=>{const xs=ps.filter(x=>(x.p.site||'四日市')===site),total=xs.reduce((s,x)=>s+x.m.total,0),correct=xs.reduce((s,x)=>s+x.m.correct,0),ts=xs.filter(x=>x.m.seconds!==null);return {site,n:xs.length,total,rate:total?Math.round(correct/total*100):null,time:ts.length?Math.round(ts.reduce((s,x)=>s+x.m.seconds,0)/ts.length):null,timed:ts.length};});
 return `<section class="manager-section comparison"><div class="manager-section-head"><div><h2>学習状況の比較</h2><p>各端末の最新提出時点の累計。提出の重複は加算しません。</p></div><label>並び順<select id="metric-sort"><option value="rate" ${sort==='rate'?'selected':''}>正解率</option><option value="total" ${sort==='total'?'selected':''}>回答数</option><option value="seconds" ${sort==='seconds'?'selected':''}>学習時間</option></select></label></div><div class="player-table-wrap"><table class="player-table"><thead><tr><th>拠点</th><th>名前</th><th>正解率</th><th>回答数</th><th>学習時間</th></tr></thead><tbody>${ps.map(({p,m})=>`<tr data-metric-person="${esc(p.key)}" tabindex="0"><td>${esc(p.site)}</td><td>${esc(p.name)}</td><td><b>${m.rate==null?'—':m.rate+'%'}</b></td><td>${m.total.toLocaleString()}問</td><td>${time(m.seconds)}${m.partial?'（一部）':''}</td></tr>`).join('')}</tbody></table></div><h3>拠点別比較</h3><div class="player-table-wrap"><table class="player-table"><thead><tr><th>拠点</th><th>人数</th><th>正解率</th><th>回答数／人</th><th>学習時間／計測者</th></tr></thead><tbody>${sites.map(s=>`<tr><td>${esc(s.site)}</td><td>${s.n}人</td><td>${s.rate==null?'—':s.rate+'%'}</td><td>${Math.round(s.total/s.n).toLocaleString()}問</td><td>${time(s.time)}${s.timed?`（${s.timed}人）`:''}</td></tr>`).join('')}</tbody></table></div><p class="manager-empty-small">正解率＝正解数÷回答数。学習時間は更新後の問題画面で計測し、画面非表示・2分以上の無操作を除きます。旧データは未計測。未提出分は含みません。</p></section>`;
 }
 function bind(root,render,open){root.querySelector('#metric-sort')?.addEventListener('change',e=>{sort=e.target.value;render();});root.querySelectorAll('[data-metric-person]').forEach(el=>{const go=()=>open(el.dataset.metricPerson);el.onclick=go;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}};});}
 window.SKIMARU_METRICS={html,bind,metrics,time};
})();
