"use strict";
(()=>{
 const config=window.SKIMARU_SUPABASE||{},labels={received:'受付済み',working:'対応中',fixed:'修正済み'},sites=['四日市','石岡','足利','水戸','真岡','門真','北九州'];
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const read=k=>{try{return JSON.parse(localStorage.getItem(k)||'{}')||{};}catch{return {};}};
 const date=x=>new Date(x).toLocaleString('ja-JP');let launcher,dialog,polling=false;
 function actor(){const dev=window.SKIMARU_SUPPORT_DEVELOPER?.();if(dev)return {role:'developer',identity:'',token:'',bearer:dev};
  const manager=read('skimaru-manager-identity-v1613'),player=read('skimaru-registration-v13');
  if((location.pathname.endsWith('/viewer.html')||readRole()==='manager')&&manager.manager_no&&manager.token)return {role:'manager',identity:manager.manager_no,token:manager.token};
  if(player.playerNo&&player.token&&player.confirmed)return {role:'player',identity:player.playerNo,token:player.token};
  return {role:'guest',identity:'',token:''};
 }
 function readRole(){try{return localStorage.getItem('skimaru-role');}catch{return '';}}
 async function rpc(action,data={},a=actor()){if(!config.url||!config.publishableKey)throw Error('接続設定がありません。');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),20000);
  try{const res=await fetch(config.url+'/rest/v1/rpc/skimaru_support',{method:'POST',headers:{apikey:config.publishableKey,'Content-Type':'application/json',...(a.bearer?{Authorization:'Bearer '+a.bearer}:{})},body:JSON.stringify({p_action:action,p_role:a.role,p_identity:a.identity,p_token:a.token,p_data:data}),signal:controller.signal,cache:'no-store'});const j=await res.json();if(!res.ok)throw Error(j.message==='rate_limited'?'送信回数が多いため、少し待ってお試しください。':'取得・保存できませんでした。通信とログイン状態を確認してください。');return j;}catch(e){if(e.name==='AbortError')throw Error('通信が時間切れになりました。再度お試しください。');throw e;}finally{clearTimeout(timer);}}
 function open(title){dialog?.close();const d=document.createElement('dialog');d.className='support-dialog';d.innerHTML=`<header><h2>${esc(title)}</h2><button type="button" aria-label="閉じる">×</button></header><div class="support-content"></div><p class="support-status" role="status" aria-live="polite"></p>`;document.body.append(d);dialog=d;d.querySelector('header button').onclick=()=>d.close();d.addEventListener('close',()=>{d.remove();if(dialog===d)dialog=null;});d.showModal();return d;}
 function error(d,e){if(d.isConnected)d.querySelector('.support-status').textContent=e.message||'処理できませんでした。';}
 async function mailbox(){const a=actor(),d=open('開発者からのメッセージ');d.querySelector('.support-status').textContent='読み込み中…';try{const messages=await rpc('mail',{},a);if(!d.isConnected)return;const host=d.querySelector('.support-content');host.innerHTML=messages.length?messages.map(m=>`<article><h3>${esc(m.title)}</h3><small>${esc(date(m.created_at))}</small><p>${esc(m.body)}</p>${a.role==='developer'?`<button data-hide="${esc(m.id)}">公開を終了</button>`:''}</article>`).join(''):'<p>メッセージはありません。</p>';d.querySelector('.support-status').textContent='';if(a.role!=='guest')await rpc('read_mail',{},a);else try{localStorage.setItem('skimaru-mail-seen-v1626',new Date().toISOString());}catch{}
  host.querySelectorAll('[data-hide]').forEach(b=>b.onclick=async()=>{if(!confirm('このメッセージの公開を終了しますか？'))return;try{await rpc('unpublish',{id:b.dataset.hide},a);mailbox();}catch(e){error(d,e);}});
  if(a.role==='developer'){const b=document.createElement('button');b.textContent='新しいメッセージを作る';b.onclick=compose;host.prepend(b);}refresh();}catch(e){error(d,e);}}
 async function photo(file){if(!/^image\//.test(file.type)||file.size>15000000)throw Error('15MB以下の写真・スクリーンショットを選んでください。');const url=URL.createObjectURL(file);try{const img=new Image();img.src=url;await new Promise((ok,no)=>{img.onload=ok;img.onerror=()=>no(Error('この画像を読めませんでした。JPEGかPNGでお試しください。'));});if(!img.naturalWidth||img.naturalWidth*img.naturalHeight>50000000)throw Error('画像が大きすぎます。スクリーンショットでお試しください。');const canvas=document.createElement('canvas'),ratio=Math.min(1,1400/Math.max(img.naturalWidth,img.naturalHeight));canvas.width=Math.round(img.naturalWidth*ratio);canvas.height=Math.round(img.naturalHeight*ratio);const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);let result=canvas.toDataURL('image/jpeg',.7);if(result.length>580000)result=canvas.toDataURL('image/jpeg',.45);if(result.length>580000)throw Error('画像を圧縮できませんでした。小さい写真でお試しください。');return result;}finally{URL.revokeObjectURL(url);}}
 function report(){const a=actor();if(a.role==='developer')return reports();const d=open('不具合を開発者へ報告');const host=d.querySelector('.support-content');if(a.role==='guest'){host.textContent='プレイヤーまたはマネージャーの登録後に報告できます。';return;}
  host.innerHTML='<form><label>件名<input name="title" required maxlength="100"></label><label>起きたこと・操作手順<textarea name="body" required maxlength="3000"></textarea></label><label>写真（3枚まで）<input name="photos" type="file" accept="image/*" multiple></label><small>写真の位置情報は送信しません。個人情報が写っていないか確認してください。</small><footer><button class="support-primary" type="submit">送信する</button><button type="button" data-reports>自分の報告・対応状況</button></footer></form>';host.querySelector('[data-reports]').onclick=reports;const id=crypto.randomUUID();host.querySelector('form').onsubmit=async e=>{e.preventDefault();const form=e.target,b=form.querySelector('[type=submit]');if(b.disabled)return;b.disabled=true;d.querySelector('.support-status').textContent='送信中…';try{const files=[...form.elements.photos.files];if(files.length>3)throw Error('写真は3枚までです。');const photos=[];for(const f of files)photos.push(await photo(f));await rpc('submit',{id,title:form.elements.title.value,body:form.elements.body.value,photos,context:{page:location.pathname,device:navigator.userAgent}},a);if(d.isConnected){host.innerHTML='<p>送信しました。開発者の返信と対応状況は「報告・対応状況」で確認できます。</p>';d.querySelector('.support-status').textContent='';}refresh();}catch(e){error(d,e);}finally{b.disabled=false;}};
 }
 async function reports(){const a=actor(),d=open(a.role==='developer'?'届いた不具合報告':'自分の報告・対応状況');try{const list=await rpc('reports',{},a);if(!d.isConnected)return;const host=d.querySelector('.support-content');host.innerHTML=list.length?list.map(r=>`<article><button data-report="${esc(r.id)}">${r.unread?'● ':''}${esc(r.title)}</button><small>${esc(labels[r.status])} ／ ${esc(date(r.updated_at))}${a.role==='developer'?' ／ '+esc(r.site)+' '+esc(r.owner_name):''}</small></article>`).join(''):'<p>報告はありません。</p>';host.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>detail(b.dataset.report,a));}catch(e){error(d,e);}}
 async function detail(id,a){const d=open('報告の詳細');try{const r=await rpc('detail',{id},a);if(!d.isConnected)return;const host=d.querySelector('.support-content');host.innerHTML=`<article><h3>${esc(r.title)}</h3><small>${esc(labels[r.status])} ／ ${esc(date(r.created_at))}</small><p>${esc(r.body)}</p><small>${esc(r.context?.page)} ／ ${esc(r.context?.device)}</small><div data-photos></div></article><h3>開発者の対応履歴</h3>${r.updates.length?r.updates.map(u=>`<article><small>${esc(date(u.at))} ／ ${esc(labels[u.status])} ${esc(u.version)}</small><p>${esc(u.reply)}</p></article>`).join(''):'<p>開発者からの更新はまだありません。</p>'}`;
  for(const src of r.photos||[]){if(!/^data:image\/jpeg;base64,[A-Za-z0-9+/=\s]+$/.test(src))continue;const img=document.createElement('img');img.src=src;img.alt='報告者の添付写真';host.querySelector('[data-photos]').append(img);}
  if(a.role==='developer'){host.insertAdjacentHTML('beforeend',`<form><label>対応状況<select name="status">${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${k===r.status?'selected':''}>${v}</option>`).join('')}</select></label><label>修正版の番号<input name="version" maxlength="50" value="${esc(r.version)}"></label><label>報告者への返信<textarea name="reply" maxlength="3000">${esc(r.reply)}</textarea></label><button type="submit" class="support-primary">対応状況を更新する</button></form>`);host.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.target,b=f.querySelector('button');b.disabled=true;try{await rpc('update',{id,status:f.elements.status.value,reply:f.elements.reply.value,version:f.elements.version.value},a);detail(id,a);}catch(e){error(d,e);}finally{b.disabled=false;}};}refresh();}catch(e){error(d,e);}}
 function compose(){const a=actor(),d=open('開発者メッセージを作る'),host=d.querySelector('.support-content');host.innerHTML=`<form><label>件名<input name="title" required maxlength="100"></label><label>本文<textarea name="body" required maxlength="3000"></textarea></label><label>届ける相手<select name="audience"><option value="all">全員</option><option value="player">プレイヤー</option><option value="manager">マネージャー</option></select></label><label>拠点<select name="site"><option value="">全拠点</option>${sites.map(s=>`<option>${s}</option>`).join('')}</select></label><button type="submit" class="support-primary">公開する</button></form>`;host.querySelector('form').onsubmit=async e=>{e.preventDefault();if(!confirm('この内容をタイトル画面のメッセージボックスへ公開しますか？'))return;const f=e.target,b=f.querySelector('button');b.disabled=true;try{await rpc('publish',{title:f.elements.title.value,body:f.elements.body.value,audience:f.elements.audience.value,site:f.elements.site.value},a);mailbox();}catch(e){error(d,e);}finally{b.disabled=false;}};}
 async function refresh(){if(polling||document.hidden||!launcher?.isConnected)return;const a=actor();if(location.pathname.endsWith('/admin.html')&&a.role!=='developer')return;launcher.querySelector('[data-report]').textContent=a.role==='developer'?'メッセージを作成':'不具合を報告';launcher.querySelector('[data-report]').onclick=a.role==='developer'?compose:report;polling=true;try{const mail=await rpc('mail',{},a);let count=mail.filter(m=>m.unread&&(a.role!=='guest'||new Date(m.created_at)>new Date(localStorage.getItem('skimaru-mail-seen-v1626')||0))).length;launcher.querySelector('[data-mail]').textContent='メッセージ'+(count?'（'+count+'）':'');if(a.role!=='guest'){const rs=await rpc('reports',{},a);count=rs.filter(r=>r.unread).length;launcher.querySelector('[data-reports]').textContent=(a.role==='developer'?'不具合通知':'報告・対応状況')+(count?'（'+count+'）':'');}}catch{/* Optional network feature must not block learning. */}finally{polling=false;}}
 function mount(){const home=document.querySelector('.unified-home [data-support-host]');if(home&&launcher?.isConnected){if(launcher.parentElement!==home)home.append(launcher);return;}const host=home||document.querySelector('.title-shell,.manager-pad,.rollout-tools')||(document.body.classList.contains('grade1-app')&&document.getElementById('settings-switches')?.closest('.pad'))||document.querySelector('#pt-home .practical-pad,#sc-set .pad .scroll,#sc-set .pad');if(!host||launcher?.isConnected)return;launcher=document.createElement('nav');launcher.className='support-launchers';launcher.setAttribute('aria-label','連絡と不具合報告');launcher.innerHTML='<button type="button" data-mail>メッセージ</button><button type="button" data-report>不具合を報告</button><button type="button" data-reports>報告・対応状況</button>';host.classList.contains('manager-pad')?host.prepend(launcher):host.append(launcher);launcher.querySelector('[data-mail]').onclick=mailbox;launcher.querySelector('[data-report]').onclick=report;launcher.querySelector('[data-reports]').onclick=reports;refresh();}
 function init(){mount();let queued=false;new MutationObserver(()=>{if(!queued){queued=true;requestAnimationFrame(()=>{queued=false;mount();});}}).observe(document.body,{childList:true,subtree:true});setInterval(refresh,60000);document.addEventListener('visibilitychange',refresh);window.addEventListener('skimaru-profile',refresh);document.getElementById('login-btn')?.addEventListener('click',()=>setTimeout(refresh,5000));}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
